### ISSUE TITLE
[Proposal] Optional prop for static container width

### ISSUE THREAD

**Issue by thejettdurham** [saleel/react-native-super-grid#10]
Great work on this component! It saved me a good amount of time designing a responsive grid component from the ground up. I did have one small issue with it: the noticeable flicker between when the component is constructed (before it knows the width of its parent) and after it's onLayout event fires. I understand why this happens and that there's not a good general solution for it, but this can be avoided if the container width could be passed to the GridView as a prop.

My use case is rendering a GridView into a container that is half the width of the display, and that width can't be changed at runtime (orientation is locked to landscape). The actual width of this container will vary between devices, but it's absolute width can always be calculated at runtime by `Dimensions.get('window').width / 2`, without the need for `onLayout` events. If I could pass this calculation to GridView as a prop, it could be used to initialize the GridView's state, and the subsequent `onLayout` triggers could be skipped. In this case, the grid will render as expected the first time without flickering.

Does this sound useful in general, or am I potentially using the wrong component to accomplish this? If this does sound good, I have an implementation I can provide via a PR.

Thanks again!

**Comment by saleel** [comment]
Hi @thejettdurham , 

Sorry for the delay in response, I am on a trip.

Initially the container width is based on full width of device and then adjusted on onLayout. As you said if there is a prop, it can be passed to `this.getDimensions()` call in the constructor. If the prop is not passed, then the current behavior can be left intact.

I don't think this is bad use case. I would appreciate a PR. Please make sure its fully backward compatible.

Thanks :-)
