### ISSUE TITLE
Type mismatch when using with typescript

### ISSUE THREAD

**Issue by Plumillon** [saleel/react-native-super-grid#107]
I got a type mismatch in `renderSectionHeader` for `SectionGrid` :
`  return (
    <SectionGrid
      itemDimension={100}
      spacing={18}
      sections={items}
      renderItem={renderItem}
      renderSectionHeader={renderSectionHeader}
    />
  );`

`  const renderSectionHeader = ({
    section,
  }: {
    section: SectionItem<Item>;
  }) => {
    return (
      section.title !== null &&
      section.title.length > 0 && (
        <SectionWrapper>
          <SectionLine />
          <SectionTitle>{section.title}</SectionTitle>
          <SectionLine />
        </SectionWrapper>
      )
    );
  };`

Where `item` is :
`export interface Item {
  picture: string;
  title: string;
  id: string;
}`

Error is :
`No overload matches this call.
  Overload 1 of 2, '(props: Readonly<SectionGridProps<Item>>): SectionGrid<Item>', gave the following error.
    Type '({ section, }: { section: SectionItem<Item>; }) => false | Element' is not assignable to type '(info: { section: SectionListData<Item>; }) => ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)> | null'.
      Types of parameters '__0' and 'info' are incompatible.
        Type '{ section: SectionListData<Item>; }' is not assignable to type '{ section: SectionItem<Item>; }'.
          Types of property 'section' are incompatible.
            Property 'title' is missing in type 'SectionListData<Item>' but required in type 'SectionItem<Item>'.`

**Comment by saleel** [comment]
I believe #106  will fix this (update to version 3.1.1). If not reopen.
