### ISSUE TITLE
componentWillReceiveProps deprecated in React 16+

### ISSUE THREAD

**Issue by mathias5r** [saleel/react-native-super-grid#108]
I got the follow warning when I upgraded the react-native to version 59.7 and react to 16.0
![Captura de Tela 2019-10-04 às 18 16 33](https://user-images.githubusercontent.com/15868862/66240526-444e9780-e6d3-11e9-810a-b4985fa8dac5.png)

**Comment by saleel** [comment]
Which version of SuperGrid are you using? `componentWillReceiveProps` is no longer used in this library. I believe I removed it long back when it was depreciated.

If you are using older version, please update and try.
