### ISSUE TITLE
So much blank space at bottom

### ISSUE THREAD

**Issue by boypanjaitan16** [saleel/react-native-super-grid#110]
Why there is so much black space at the bottom? and how I reduce it ?
Please help
![Screenshot_1574584707](https://user-images.githubusercontent.com/46698152/69492127-e408f480-0ed0-11ea-8ece-b273fd6727ca.png)

**Comment by saleel** [comment]
This looks like something you can achieve by modifying styles of GridView.
Try removing `flex: 1,` from gridView styles.
