### ISSUE TITLE
array.reduce is not a function 

### ISSUE THREAD

**Issue by stepupithubapp** [saleel/react-native-super-grid#111]
<SectionGrid
                spacing={0}
                itemDimension={scale(33)}
                sections={data}
                extraData={data}
                renderItem={({item, section, index}) => (<AllPixeachfile
                    item={item}
                    index={index}
                    openImage={this._openImage}
                    />)}
                renderSectionHeader={({section}) => (
                    <View style={{
                        marginVertical: scale(10)
                    }}><Text style={
                    styles.titleContainer} ellipsizeMode='tail' numberOfLines={1}>{section.key}</Text></View>
                )}
                />

**Comment by saleel** [comment]
I guess the `data` passed to sections prop has invalid signature. It should be same as that of SectionList - [https://facebook.github.io/react-native/docs/sectionlist](https://facebook.github.io/react-native/docs/sectionlist)
