### ISSUE TITLE
how to give scroll to end property in sectiongrid ??

### ISSUE THREAD

**Issue by stepupithubapp** [saleel/react-native-super-grid#112]
<SectionGrid
                spacing={0}
                itemDimension={scale(68)}
                sections={data}
                extraData={this.state}
                listkey = {(item, index) => index + ''}
                renderItem={({item, index}) => (<AllPixeachfile
                    item={item}
                    index={index}
                    openImage={this._openImage}
                    />)}
                renderSectionHeader={({section}) => (
                    <View style={{
                        marginVertical: scale(15),
                        marginLeft: scale(5)
                    }}><Text style={
                    styles.headerText} ellipsizeMode='tail' numberOfLines={1}>{section.key}</Text></View>
                )}
                />

**Comment by saleel** [comment]
You can add a `ref` to SectionGrid and call the `scrollToEnd` property. Internally SectionGrid is SectionList, which is in fact implementation of ScrollView, [scrollToEnd](https://facebook.github.io/react-native/docs/scrollview#scrolltoend) should work
