### ISSUE TITLE
Dinamic item dimensions

### ISSUE THREAD

**Issue by RodolfoGS** [saleel/react-native-super-grid#113]
Hi, I need to change the dimension of specific items of my list.

My use case is the follow:
I need to create a 2 item columns BUT after certain number of rows (example each 4 rows) I need to add a banner ad that have 100% of the screen width (2 columns).

**Example**:
```
| item | item |
| item | item |
|    banner   |
| item | item |
| item | item |
|    banner   |
| item | item |
| item | item |
```

Are any solution to do this? I could make this if I pass a function to  the`itemDimension` param and return the width of each item using your index, but this is not supported for the `FlatGrid` compoment.

I can use `SectionGrid` headers, but I don't want to keep this separators fixed in the header.

Any suggestion? Thank lot!

**Comment by aleciogomes** [comment]
Since `SectionGrid` internally renders a `SectionList` and forward any unhandled prop, I think you can pass the `stickySectionHeadersEnabled={false}` prop to `SectionGrid` component to prevent the header sticking.

**Comment by RodolfoGS** [comment]
@aleciogomes oh really?, I'll try that! In a few hours tell you my experience. Thanks lot

**Comment by RodolfoGS** [comment]
@aleciogomes works perfect your solution, thank you so much bro! 🎉
