### ISSUE TITLE
Resize Issue

### ISSUE THREAD

**Issue by karanpratapsingh** [saleel/react-native-super-grid#114]
Hey @saleel big fan of your work, but I am facing an resize issue, I am using this package in one of my project: https://github.com/karanpratapsingh/Proximity and I am facing the issue below.

It's shifting the grid when rendering, is there a way to fix this?
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29705703/70859163-f8229d80-1f34-11ea-86ee-fc56a9c8a7c7.gif)

Thank you

**Comment by karanpratapsingh** [comment]
fixed using `staticDimensions` props

**Comment by saleel** [comment]
Sorry, I couldn't reply earlier. 
Good to know you have fixed the problem. If the available width for the grid can be varying, then `staticDimension` is probably the solution.

Closing the issue.
