### ISSUE TITLE
Scroll to last index automatic when first time screen open

### ISSUE THREAD

**Issue by vnanaware** [saleel/react-native-super-grid#118]
how to resolve this issue in 
import { FlatGrid } from 'react-native-super-grid';

**Comment by saleel** [comment]
Most likely this is not an issue with FlatGrid. I need to see code/demo to give any help.
Are you dynamically adding new items to the grid? Check this issue https://github.com/facebook/react-native/issues/25239

**Comment by vnanaware** [comment]
Yes adding new items dynamically...

**Comment by saleel** [comment]
Look like this is the behavior of FlatList, and there is no native way to disable it. There are many workaround if you search online.
Check the link I have above, and [this](https://stackoverflow.com/questions/43611485/prevent-flatlist-from-scrolling-when-new-items-are-added) for example
