### ISSUE TITLE
TypeError: undefined is not a function (near '...(0, _utils.calculateDimensions)...')

### ISSUE THREAD

**Issue by JosephMulder** [saleel/react-native-super-grid#119]
Using the latest version I get an error when trying run the application with FlatGrid
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-super-grid": "^3.1.2"

E/ReactNativeJS: TypeError: undefined is not a function (near '...(0, _utils.calculateDimensions)...')
    
    This error is located at:
        in NavigationContainer (at App.js:350)
        in App (at renderApplication.js:40)
        in RCTView (at AppContainer.js:101)
        in RCTView (at AppContainer.js:119)
        in AppContainer (at renderApplication.js:39)

**Comment by saleel** [comment]
Can you provide full stack trace and the code where you are using FlatGrid?

It looks like you have not passed the props correctly.
