### ISSUE TITLE
Please export "scrollToLocation"

### ISSUE THREAD

**Issue by gds3k3** [saleel/react-native-super-grid#120]
Great work with this component, thank you!

Please export "scrollToLocation" prop of sectionList.

Thank you again.

**Comment by saleel** [comment]
Sorry for the delay. 

Do you mean to export a method of SectionList in index.d.ts? 

Is it a new prop? I don't use TS myself. If you can submit a PR, I will merge it.

**Comment by saleel** [comment]
@Grohden Can you have a look in to this please when you have some time.

If its already handled, please close this PR.

**Comment by Grohden** [comment]
@saleel gonna take a look in a few hours

**Comment by Grohden** [comment]
@saleel I don't see these methods on the supergrid sources, they're only on RN's section/flat list.
Is there any ref forwading for the original section/list in the lib? 
If not, the easiest way would be either forward the original ref or create another prop (like `originalListRef`) and just type it on TS...

**Comment by saleel** [comment]
From what I understand we need to add `scrollToLocation` here - https://github.com/saleel/react-native-super-grid/blob/master/index.d.ts#L88
I don't use TS for myself, so I am not sure.

Moreover I just noticed [scrollToLocation of SectionList](https://reactnative.dev/docs/0.48/sectionlist#scrolltolocation) takes `sectionIndex` and `itemIndex`. `itemIndex` would be the row index in case of SectionGrid, so this functionality might not work as expected.

**Comment by Grohden** [comment]
@saleel
In that line I **omit** the RN's unsupported props, so every other **prop** is available

The op request is to add the original RN **methods**

I'm not sure if it's desired, but these **methods** should be part of super grid implementation (on super grid classes)... The op would call them using a ref like `superGridRef.scrollToLocation({ sectionIndex: 1, rowIndex: 1 })`

But I think that they would need to be implemented on the lib side, and not just forwarded to RN lists ref, as you said the functionality would not work as expected if we just forward the RN's list ref

**Comment by saleel** [comment]
Ah ok. I didn't notice it properly. I thought we are adding the required props over there. Also forwardRefs wont solve the functionality.

@gds3k3 This feature is not there right now. Are you interested in doing a PR for it? You will have to do something like creating a new scrollToLocation prop which will calculate the correct rowIndex for given itemIndex and call the internal scrollToLocation with that itemIndex.

**Comment by ogroppo** [comment]
Is this issue progressing? Very interested. Thanks

**Comment by saleel** [comment]
@ogroppo Looks like this feature has to be implemented. I will add it after or as a part of v4 release. 
Probably in a week.

**Comment by ogroppo** [comment]
@saleel is there any other scroll method available at the moment?

**Comment by saleel** [comment]
There is no correct solution right now.

Since all the props are passed down to SectionList, you can try using scrollToLocation. sectionIndex will work, but itemIndex will not the be real index as in your data. You can try giving itemIndex as 0 so it at-least scroll to top of that section. You can also try something like `itemIndex: Math.round(index / x)` where `x` is the number of items that are usually rendered in most devices. Again, this is a hack for now and might not work properly.

Also, they mentioned `getItemLayout` has to be specified in order to be scrolled outside the render window. So note sure how effective it will be.

**Comment by gds3k3** [comment]
Hi @saleel. Thanks for your answer, I think there is enough info to workaround until final implementation. Looking forward for V4.
Sorry I can´t work on a working for everyone PR right now.
