### ISSUE TITLE
Is it refreshable ?

### ISSUE THREAD

**Issue by boypanjaitan16** [saleel/react-native-super-grid#121]
I do quick look on the documentation, but I dont see relatable things to this. Is it possible ?

**Comment by saleel** [comment]
Yes. In the parent component if you are maintaining the data in a state, then as the state is updated, the gridView will re-render. Just like FlatList or SectionList.

**Comment by boypanjaitan16** [comment]
I mean something like drag down to refresh like flatlist

**Comment by saleel** [comment]
FlatGrid component is build on top of FlatList. So all additional props are passed down to FlatList - including the `onRefresh` method. So it should work.
