### ISSUE TITLE
Allow for providing item key

### ISSUE THREAD

**Issue by bernalmurcia** [saleel/react-native-super-grid#124]
Hi, thanks for this great library! 

I dynamically filter data items that go into the FlatGrid, and this results in unexpected behavior because item keys are based on their index, not on them being unique keys, a result of this line:

https://github.com/saleel/react-native-super-grid/blob/master/FlatGrid.js#L78

It'd be great if a key could be supplied as part of the item data, I've only tested for my particular scenario but to make this work correctly I just needed to change:

> key={`item_${(rowIndex` * itemsPerRow) + i}`}

to

> key={item.key || `item_${(rowIndex * itemsPerRow) + i}`}

That worked for me. As a note, I believe it's best practice in React not to rely on indexes:
https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

**Comment by saleel** [comment]
Yes, best practice is not to use indices.
It was part of a big [PR](https://github.com/saleel/react-native-super-grid/pull/32/commits/c466ae990ffd4da9aa61c8e4262884895f602157#diff-168726dbe96b3ce427e7fedce31bb0bcR112) which was closed in favor of another for some other reasons if I remember correctly, and this functionality didn't get implemented.

The right solution would be to get `keyExtractor` function as a prop and use it (like in FlatList). Now, one FlatList row here is collection of multiple `items`. So we will have to join extracted keys from all those items in FlatList's `keyExtractor` prop. In the `.map` method you mentioned we can call they `keyExtractor` directly.

Are you interested in making a PR for this? If not,  I will do.
