### ISSUE TITLE
render an view between flatList items in react native

### ISSUE THREAD

**Issue by JZorina** [saleel/react-native-super-grid#125]
i am  rendering a <FlatList/> and after the first two items i want to render some view , and then the rest of the items - is there any way to do that in react native?

this is the list: <FlatList
                style={Style.mentaBenefitsList}
                data={MentaItems}
                numColumns={2}
                renderItem={({ item }, index) =>
                    <AddibleItem
                        itemName={item.name}
                        itemImage={item.image}
                        itemPrice={item.price}
                        itemTimeToEnd={item.timeToEnd}
                        AddToFavorites={this.AddToFavorites}
                        handlePress={this.handlePress}
                        key={index}
                    />}

mentaBenefitsList: {
        alignSelf: 'center',
        zIndex: 1
    },
this is the view: 
 
<View style={Style.ImageMentaBenefitContainer}>
                <Image/>
            </View>

  ImageMentaBenefitContainer: {
        zIndex: 1,
        borderRadius: 15,
        backgroundColor: 'pink',
        height: 250,
        width: '100%'
    }

**Comment by saleel** [comment]
I am not sure if I understand you correctly. Insert a dummy object to the FlatList data array wherever you want to use custom view. And in the renderRow method, check if the dummy item is in the callback and render whatever you want.
Anyway, i don't think it is not in the scope of this library. Closing.
