### ISSUE TITLE
How to handle an empty state?

### ISSUE THREAD

**Issue by bitttttten** [saleel/react-native-super-grid#126]
Just want to say, really loving the library! Are there any good practises for handling empty states?

Like when the array being passed to `items` is empty? I want to display a message if the list is empty and to keep the refresh control and header that I have.

**Comment by saleel** [comment]
Right now, nothing. Its a good feature though.
emptyStateComponent can be a prop and can be rendered when the items is empty.

Are you interested in doing a PR?

**Comment by saleel** [comment]
Glad to hear that :-)

Right now, nothing. Its a good feature though.
emptyStateComponent can be a prop and can be rendered when the items is empty.

Are you interested in doing a PR?

**Comment by bitttttten** [comment]
I'll see how I get on!

**Comment by bitttttten** [comment]
Turns out this already exist and the library supports it since you pass all the props to the native component: https://reactnative.dev/docs/flatlist#listemptycomponent.

😅

**Comment by saleel** [comment]
Ah, its already there in FlatList 😀
Thanks 👍
