### ISSUE TITLE
How to avoid margin of items in the left, right, top or bottom?

### ISSUE THREAD

**Issue by thanh-taro** [saleel/react-native-super-grid#128]
By default, the FlatGrid will add calculate and make margins between items to the left, right, top and bottom of the parent view. In my case, I need items fill full the grid, means avoid those margins.
Is there an options to config?

![image](https://user-images.githubusercontent.com/9627078/79062427-80873400-7cc4-11ea-8c30-42f73b8bf7c9.png)

**Comment by saleel** [comment]
The spacing between the items is defined by the `spacing` prop. This will add spacing between the items and for the edge as well.
If you don't want spacing on edges, you can set negative margin for the grid view (with the same number you gave for `spacing` prop).

[https://codesandbox.io/s/priceless-carson-3kkne](https://codesandbox.io/s/priceless-carson-3kkne)

**Comment by saleel** [comment]
Closing the issue. Hope it is resolved.

**Comment by thanh-taro** [comment]
I got your idea. I'll try. Thank you a lot.

**Comment by DevHamx** [comment]
> The spacing between the items is defined by the `spacing` prop. This will add spacing between the items and for the edge as well.
> If you don't want spacing on edges, you can set negative margin for the grid view (with the same number you gave for `spacing` prop).
> 
> https://codesandbox.io/s/priceless-carson-3kkne

worked with `itemContainerStyle={{margin:-10}}`

**Comment by saleel** [comment]
> > The spacing between the items is defined by the `spacing` prop. This will add spacing between the items and for the edge as well.
> > If you don't want spacing on edges, you can set negative margin for the grid view (with the same number you gave for `spacing` prop).
> > https://codesandbox.io/s/priceless-carson-3kkne
> 
> worked with `itemContainerStyle={{margin:-10}}`

Yea. That would work as well. Thanks
