### ISSUE TITLE
View.PropTypes deprecated APK release crash on 0.49 ++

### ISSUE THREAD

**Issue by caudaganesh** [saleel/react-native-super-grid#13]
The current package not working with 0.49++, the problem caused by View.PropTypes deprecated.
solution :

- [x] add `import { View, ListView, Dimensions, ViewPropTypes } from 'react-native';`
- [x] change the `style: View.PropTypes.style` to `style: ViewPropTypes.style,
`

**Comment by caudaganesh** [comment]
@saleel can you give me guidelines to fix this sir? so i can help you working with this issue,  sorry i am relatively new in making package

**Comment by saleel** [comment]
In https://github.com/saleel/react-native-super-grid/blob/master/index.js Line 103 we have `View.propTypes` which should be changed to `ViewPropTypes.style`

You can make the changes in your fork and send a Pull Request. I will approve it and make a new npm version that target 0.49+.

**Comment by caudaganesh** [comment]
okay, thanks a lot sir @saleel
