### ISSUE TITLE
Ability to customize rowStyle

### ISSUE THREAD

**Issue by george-moussa** [saleel/react-native-super-grid#149]
I need to reverse rows without using 'rtl', i.e. if the items list has 1, 2, 3, 4. I want '1' to be on the right side.

This can be achieved by setting flexDirection to 'row-reverse' on rowStyle. But currently rowStyle is not exposed. Is there another way to do that?

**Comment by saleel** [comment]
Option for additional row styles is not exposed currently. You can add a new prop and place it [here](https://github.com/saleel/react-native-super-grid/blob/master/FlatGrid.js#L88). I would be happy to merge a PR on this.

**Comment by sanghavan** [comment]
> Option for additional row styles is not exposed currently. You can add a new prop and place it [here](https://github.com/saleel/react-native-super-grid/blob/master/FlatGrid.js#L88). I would be happy to merge a PR on this.

Hi @saleel, I made a PR at https://github.com/saleel/react-native-super-grid/pull/151. Could you please check it.

**Comment by saleel** [comment]
PR merged. @george-moussa Use the new additionalRowStyle prop in version 4.1.0
