### ISSUE TITLE
Styling Issues

### ISSUE THREAD

**Issue by elmcapp** [saleel/react-native-super-grid#150]
3 questions
1.Long text is being wrapped. Is there any way to preview this from happening? 
2. Is there a way to make the boxes auto size with the text or make the text shrink to fit the box
3. Can we join 2 grids. Lets say that grid 1 has 3 blocks or boxes. Grid 2 has 2 boxes. Can we make both join together to get one full row of 5 boxes

**Comment by saleel** [comment]
For 1 and 2, you can style the inner component of the grid as per your needs. You can return a View component with necessary styles in the renderItem method.
For 3, you can place two FlatGrids in the page and style them to align next to each other. You will need to sort out data for both grids from outside.
