### ISSUE TITLE
How to create a onPress function in the Cards????

### ISSUE THREAD

**Issue by TanushGITHUB** [saleel/react-native-super-grid#154]
how do i craete a onPress in the card.

**Comment by saleel** [comment]
You can return your custom component with `onPress` handler in `renderItem` callback. This library only take care of the layout, you have full control on the component rendered inside.

**Comment by TanushGITHUB** [comment]
Dude, I am not an expert in react native...
So could you just give me a sample of the cards having onPress function?
Please help me out😭
