### ISSUE TITLE
Horizontal Row Items Height

### ISSUE THREAD

**Issue by omarijbara** [saleel/react-native-super-grid#158]
Many thanks for your artwork,
I would be very grateful if I could find out if this error is on my part? Or I didn't really understand the thing you meant under horizontal by Properties with 100% height.
 

>If true, the grid will be scrolling horizontally. If you want your item to fill the height when using a horizontal grid, you should give it a height of '100%'. This prop doesn't affect the SectionGrid, which only scrolls vertically.

It would be awesome if you could write it in a practical example, making all grids in same horizontal row having the **same height** respectively on same line.

https://snack.expo.io/@omarijbara/happy-fudge

![image](https://user-images.githubusercontent.com/49615980/114243565-18c60080-998d-11eb-988b-a3b54dbf9096.png)

**Comment by saleel** [comment]
@omarijbara 
That prop is only for FlatGrid. SectionGrid cannot be rendered horizontally. AFAIK native SectionList also cannot be put in horizontal mode.

**Comment by omarijbara** [comment]
Many Many Thanks!
