### ISSUE TITLE
How to remove paddings?

### ISSUE THREAD

**Issue by likeSo** [saleel/react-native-super-grid#159]
![image](https://user-images.githubusercontent.com/12247340/114981212-367cf380-9ec0-11eb-86bb-8f12b868608b.png)
![image](https://user-images.githubusercontent.com/12247340/114981228-3bda3e00-9ec0-11eb-84c8-5c02d0416bb9.png)
How can i remove the top and left padding of grid?
My grid should be left-aligned with the title equally

**Comment by saleel** [comment]
You can give negative marginLeft and marginTop to the grids style prop

**Comment by likeSo** [comment]
> You can give negative marginLeft and marginTop to the grids style prop

![image](https://user-images.githubusercontent.com/12247340/114990525-2b7b9080-9ecb-11eb-8926-f8b8cddff773.png)
Hi, marginTop and marginLeft works, but another problem coming
Items inside Grid are not filled equally (right spacing is greater than left side), could you let us just set a `numberOfColumns` and let items fill equally? here is my code:
```tsx
<FlatGrid
          data={[0, 1, 2, 3, 4, 5, 6, 7, 8]}
          itemDimension={100}
          renderItem={() => <HomeGoodsCell />}
          keyExtractor={(item, index) => index.toString()}
          style={{marginLeft: -10, marginTop: -10}}
        />
```

**Comment by saleel** [comment]
If you applied negative margin, there would be more space on right side. As of now there is no way to give a different spacing for one side alone.
If the requirement is to align with the title, how about adding a marginLeft to the title and make it align with the first item? You can also remove the padding of your outer container so there is no added space on either side.

As of `numberOfColumns` prop, this library dont work like that, but I am sure there would be many that work this way. Here the idea is to dynamically calculate the values and responsively fill the items, so same code could work on phones and tablets of all sizes.
