### ISSUE TITLE
Property 'onEndThreshold' does not exist on type

### ISSUE THREAD

**Issue by thevishnupradeep** [saleel/react-native-super-grid#165]
I am seeing an error `Property 'onEndThreshold' does not exist on type...` when trying to implement infinite scroll.

```
<FlatGrid itemDimension={150} data={data}
renderItem={renderAS} keyExtractor={({ ID }) => ID}
onEndReached={onEndReached} onEndThreshold={10}  />
```

Also, I can confirm that the onEndThreshold doesn't work. I tried different values.

**Comment by saleel** [comment]
I think it should be [onEndReachedThreshold](https://reactnative.dev/docs/flatlist#onendreachedthreshold)

**Comment by thevishnupradeep** [comment]
Yes... That fixed type problem 😅
Thank you.
