### ISSUE TITLE
Failed prop type: Invalid prop `style` of type `number` supplied to `FlatGrid`, expected `object`.

### ISSUE THREAD

**Issue by siarheipashkevich** [saleel/react-native-super-grid#166]
Hi all. 

I have the `styles.js` file:
```
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  gridView: {
    paddingTop: 0,
  },
});
```

And I try use this style for `FlatGrid`:
```
<FlatGrid
  ref={flatGridRef}
  data={data}
  style={styles.gridView}
  renderItem={renderItem}
  keyExtractor={getGridItemUniqueKey}
/>
```

But I'm getting en error:
```
Warning: Failed prop type: Invalid prop `style` of type `number` supplied to `FlatGrid`, expected `object`.
```

Could you please extend `style` prop for getting styles?

```
style: PropTypes.oneOfType([PropTypes.object, PropTypes.number, PropTypes.array]),
```

**Comment by saleel** [comment]
Extending the style prop to include number wont solve the problem I believe. Why is the style passed a number? It should be an object.

**Comment by siarheipashkevich** [comment]
@saleel you can try my example with two files one `index.js` and another `styles.js`. If extend style as I mentioned above then it works.

**Comment by saleel** [comment]
Yes, since you are importing the stylesheet from a different file, it will a number mapped by RN internally.

When you change style prop like you had, are you able to see the desired style changes in the UI as well? If that is the case, you can create a PR for the same.
