### ISSUE TITLE
Items in list overlapping

### ISSUE THREAD

**Issue by ricohumme** [saleel/react-native-super-grid#177]
Hi,

I have found that when rendering items it sometimes happens that the items are overlapping due to the fact the container is not growing.
When reverting back to FlatList these issue do not occur, 
Have these issues already been found by someone?
![Selectie_024](https://user-images.githubusercontent.com/11029998/147365448-30d37793-2cbf-4a31-93ae-9dda19df232d.png)

A code example where this occurs:

```
<FlatGrid
      style={styles.container}
      contentContainerStyle={{ flexGrow: 1 }}
      data={recipes}
      keyExtractor={(recipe) => recipe.id.toString()}
      renderItem={({ item: recipe }) => (
        <View style={{paddingHorizontal: 24}}>
          <RecipeCard recipe={recipe} large={true} />
        </View>
      )}
      itemDimension={isMobileDisplay ? 320 : 238}
      additionalRowStyle={[{ alignItems: "baseline" }]}
      {...props}
    />

const styles = StyleSheet.create({
  container: {
    width: "100%",
  },
  items: {
    width: "100%",
    minWidth: 238,
    minHeight: 400,
    justifyContent: "space-between",
    flex: 1,
  },
});

```
If anything else is required, please let me know.
Thanks a bunch in advance.

**Comment by saleel** [comment]
I believe its some of the styles causing the issue. Can you try removing `flex: 1` from `items` and adding it to `container`?

If that don't solve the issue, can you create an [expo snack](https://snack.expo.dev/@saleel/react-native-super-grid) reproducing the issue?

**Comment by saleel** [comment]
Btw, is this happening when you rotate the device? And once this happen does it go away immediately or stay like this?

**Comment by ricohumme** [comment]
Hi,

I tried both with and without flex. Initially I thought flex would resolve the issue, but it didn’t sadly. 
the device’s orientation is portrait and is not setup for landscape. But I am supporting web with this application as well so that is why I chose this component. 
I’ll try and setup a snack example tomorrow with some data sets. 
Fyi, I haven’t been able to reproduce this issue yet on web, just on mobile viewports (also including web using devtools)

**Comment by ricohumme** [comment]
Goodmorning!
I successfully created a reproducible snack which I could not get to fail on web, but immediately on iOS and Android.
I created a couple of dataset which you can switch through.

https://snack.expo.dev/@ricohumme/flatgrid-demo

**Comment by saleel** [comment]
I removed `additionalRowStyle={[{ alignItems: "baseline" }]}` prop and it looks fine now in both iOS and Web - [snack](https://snack.expo.dev/Blv770eed). Is that style really needed?

**Comment by ricohumme** [comment]
Thanks for that very quick reply!
It seems odd that this would trigger it, but I needed that alignment for the browser when display the cards next to each other.
Without it, the cards would not align correctly and be all over the place.
What would be your take on that ?

**Comment by ricohumme** [comment]
I could ofcourse use my variable isMobileDisplay to choose a different alignment, but I'm just curious as to why this would break it. Or maybe I just don't understand the alignItems style incorrectly

**Comment by saleel** [comment]
I am not sure if I understand. This is how it looks in the web for me
<img width="1247" alt="Screen Shot 2021-12-27 at 11 10 43 AM" src="https://user-images.githubusercontent.com/13466197/147466299-3dd9be89-f61e-4bd7-9975-7cf6e3b0138a.png">

**Comment by saleel** [comment]
Oh, I think I get you. In order for the items to have same height you can specify something like `height: 500` in the View styles.

```renderItem={({ item: recipe }) => (
        <View style={{paddingHorizontal: 24, height: 500 }}>
          <RecipeCard recipe={recipe} large={true} />
        </View>
      )}
```

**Comment by ricohumme** [comment]
This could be me trying to find the issue and passing heights in places where it should not be needed. But I am glad this resolved my issue:
I now have `additionalRowStyle={[{ alignItems: !isMobileDisplay ? "baseline" : "center" }]}` which actually works as I want it to.
