### ISSUE TITLE
StickyHeader support for SectionGrid

### ISSUE THREAD

**Issue by WenLonG12345** [saleel/react-native-super-grid#178]
Hi, thanks for this awesome library!
However, is there any support for StickyHeader for SectionGrid? Because I didnt saw documentation mentioning about this.
Thanks in advance.

**Comment by saleel** [comment]
Since SectionGrid uses SectionList internally (and pass down all the extra props), the [ListHeaderComponent](https://reactnative.dev/docs/sectionlist#listheadercomponent) prop should work. 
Please reopen if it don't.
