### ISSUE TITLE
Use Animated components instead of default one?

### ISSUE THREAD

**Issue by Ryanjso** [saleel/react-native-super-grid#190]
This is more of a question than an issue, but wondering if it's possible to tell this package to use an `<Animated.Flatlist/>` instead of a `<Flatlist/>`

https://reactnative.dev/docs/animated#animatable-components

I can create a custom animated component using the [createAnimatedComponent()](https://reactnative.dev/docs/animated#createanimatedcomponent) component, but swapping in Flatlist would be quicker and easier if possible.

Thanks for any info!

**Comment by saleel** [comment]
Hi @Ryanjso 

It is not possible currently, but I think it should be a simple change is an additional `prop`. I can merge it quickly if you can do a PR.

Ref: https://github.com/saleel/react-native-super-grid/blob/master/FlatGrid.js#L162
