### ISSUE TITLE
Grid items overlap when value passed to staticDimension updates on device rotation

### ISSUE THREAD

**Issue by whenmoon** [saleel/react-native-super-grid#195]
Hi, I am currently using the `staticDimension` prop to work around this exact issue: https://github.com/saleel/react-native-super-grid/issues/114. But when the device is rotated and the width of the screen passed to `staticDimension` changes, the layout of the grid cells in `FlatGrid` is not correct: 

https://user-images.githubusercontent.com/33122888/201152724-d0ee92da-b556-4275-b62d-5aa3744ea6e6.mov

Is there a way to fix this?

Many thanks!

**Comment by saleel** [comment]
Hey @whenmoon ,

Sorry for the delay.

Is the value passed as `staticDimension` changing when the orientation changes? It should re-render the grid when the prop change based on the code ( I have not tested this).
Without using `staticDimension` are you not able to style the parent container holding the grid and give something like (flex:1, width: 100%)? Or try using the [useWindowDimensions](https://reactnative.dev/docs/usewindowdimensions) to set the window width.

**Comment by whenmoon** [comment]
Hi @saleel thanks for the response - yes `staticDimension` is changing but seems like it is not re-rendering the grid. In the end I have used another solution (outside the library), so feel free to close the issue or maybe we can leave it open for others. Thanks for your help.

**Comment by saleel** [comment]
I had a quick check and staticDimension is re-rendering the grid like expected. Not sure why it didn't work for you.

I think I will close the issue for now.

Thanks
