### ISSUE TITLE
[QUESTION] How to make spacing only betwen items

### ISSUE THREAD

**Issue by bryantobing12** [saleel/react-native-super-grid#198]
![Screenshot 2022-11-29 at 11 22 14](https://user-images.githubusercontent.com/46083126/204438504-59400caf-a520-4db5-b595-e6fc01640c93.png)

How can we remove space outside the item? 

The only thing i care when adding spacing is add space between the items, this is something like flex gap in css

**Comment by saleel** [comment]
HEy @bryantobing12 

`spacing` prop add space outside as well. You should be able to achieve that by adding a negative margin on the parent container with `-spacing` as the value.

**Comment by bryantobing12** [comment]
Not sure why this is not by default considering many grid system i have used do that

**Comment by saleel** [comment]
The common use-case I believe would be to render the grid in full screen - where the outer padding is required (like in the example).

**Comment by exotexot** [comment]
I agree, would be nice to set inner and outer spacing in this module...
