### ISSUE TITLE
Render some items with full width

### ISSUE THREAD

**Issue by l2aelba** [saleel/react-native-super-grid#203]
Any trick to render some items with **full width**?

Right now I do something like…

```js
const { width } = Dimensions.get('window')

const ItemContent = ({ data }) => {
  return (
    <View style={ { width: data.isFull ? width: 'auto' }}>
       …
    </View>
  )
}
```

Not sure this is good.

I would like to use `{ width: "100%" }`  but did not succeed. 

Any trick?

**Comment by saleel** [comment]
This is not doable from within the library, so you would need to do some tricks like this one. I can't think of anything better - at the same time, I don't think this is a bad solution.

**Comment by l2aelba** [comment]
Thanks, so I will continue with that.
