### ISSUE TITLE
get current index while scrolling

### ISSUE THREAD

**Issue by fukemy** [saleel/react-native-super-grid#204]
Hi, thanks for useful library.
I want to get the current index while scrolling, can u give me some advices

**Comment by fukemy** [comment]
the biggest problem is I can not get each section + items height, I have only `itemPerRow` which defined before, can u suggest me how to do it? I am stucking with this since a few days

**Comment by saleel** [comment]
onScroll callback has a parameter that contains offset from the top. You can use this to determine how long has been scrolled. Since you define the itemHeight beforehand and you know it, you can divide the offset from top by the itemHeight
