### ISSUE TITLE
Could this render for some big cell and some small cell?

### ISSUE THREAD

**Issue by qixinynan** [saleel/react-native-super-grid#205]

**Comment by saleel** [comment]
No, not with the current setup. It calculates the number of items to be put on screen based on the width set for items.

Though I think width-per-item is possible, but require some significant change in the math calculations.

**Comment by qixinynan** [comment]
> No, not with the current setup. It calculates the number of items to be put on screen based on the width set for items.
> 
> 
> 
> Though I think width-per-item is possible, but require some significant change in the math calculations. 

ok，thanks！
