### ISSUE TITLE
bug load first time data in FlatGrid

### ISSUE THREAD

**Issue by kambie10** [saleel/react-native-super-grid#206]
![Screenshot_1687841440](https://github.com/saleel/react-native-super-grid/assets/38092016/97db31ad-1e5c-4aa6-b10c-26a871c8f0be)

I use flex to divide 2 columns in 1 screen, the first time I take flatgird data out of flex, how do I fix this?

**Comment by saleel** [comment]
Sorry, I did not understand. Please explain the problem and if possible, provider a sample code in expo

**Comment by nvdnvd00** [comment]
I believe this is the issue he was referring to.
The list always gets cut off slightly on the right.
![CleanShot 2023-09-18 at 20 05 02](https://github.com/saleel/react-native-super-grid/assets/17423070/d3046441-30f0-41b7-b9d4-5bfb01eb2656)

**Comment by saleel** [comment]
Do you mean there is extra padding on the right side of the grey container? Or the white space outside the right side of the container? 

Looking at the original screenshot of @kambie10 again, I think they are referring to last items of each row being cut. This could happen on initial load as the grid have full screen width and then later get the reduced width. The grid will auto arrange based on new width but there will be a small delay. If the width of the outer component is known beforehand, then we can set width style for that component and the grid container.

**Comment by nvdnvd00** [comment]
> Do you mean there is extra padding on the right side of the grey container? Or the white space outside the right side of the container?
> 
> Looking at the original screenshot of @kambie10 again, I think they are referring to last items of each row being cut. This could happen on initial load as the grid have full screen width and then later get the reduced width. The grid will auto arrange based on new width but there will be a small delay. If the width of the outer component is known beforehand, then we can set width style for that component and the grid container.

Thank you! When I set a fixed width for the parent view, the issue disappeared
