### ISSUE TITLE
I want a prop to achieve lazy load data 

### ISSUE THREAD

**Issue by YqxLzx** [saleel/react-native-super-grid#209]
Execute a function when the scroll bar is a certain distance from the bottom. Sorry, I didn't see a similar function in the document.

**Comment by saleel** [comment]
FlatGrid is on top of FlatList - so you should be able to use `onScroll` event to handle this.

**Comment by YqxLzx** [comment]
THX YOU



发自我的iPhone


------------------ Original ------------------
From: saleel ***@***.***&gt;
Date: Fri, Nov 3, 2023 2:59 AM
To: saleel/react-native-super-grid ***@***.***&gt;
Cc: Oscar Lee ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [saleel/react-native-super-grid] I want a prop to achieve lazyload data  (Issue #209)





 
Closed #209 as completed.
