### ISSUE TITLE
Request to add new features renderFooter and onEndReached

### ISSUE THREAD

**Issue by Angelk90** [saleel/react-native-super-grid#21]
@saleel : 
hi, I'm getting along very well with this module. ;)
Would it be possible to add these features?
for example to be able to carry out the pull to refresh.
```
renderFooter={this.renderFooter)}
onEndReached={this._onEndReached}
```

**Comment by saleel** [comment]
Whatever is supported in ListView should work out of the box. 

I have plans to change to FlatList, but not sure when that will be.
