### ISSUE TITLE
Warning: FlatGrid: Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead. React Native 0.74.1

### ISSUE THREAD

**Issue by kyslyi** [saleel/react-native-super-grid#217]

**Comment by legend-oe** [comment]
The same issue.
" ERROR  Warning: FlatGrid: Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead "

"expo": "51.0.0"
"react": "18.2.0"
"react-native": "0.74.1"

Temporary deleted FlatGrid.defaultProps from node_modules/react-native-super-grid/FlatGrid.js and add it props to component on use page.

**Comment by mrEuler** [comment]
Also have same issue. 
@saleel 👀

**Comment by saleel** [comment]
Ok, looks like we need to remove defaultProps and add the default values to the JS object `prop` during destructuring in the component. Shouldn't break anything for older versions of RN.

Let me know if anyone would like to do a PR.

**Comment by mohammadlth** [comment]
same issue
@saleel

**Comment by saleel** [comment]
Just published Version 6.0.0 - `react-native-super-grid@6.0.0`. It should fix the issue.

Can someone please try and update here?

**Comment by saleel** [comment]
Published version 6.0.1. Can you some please try and update here.

**Comment by EssiJunior** [comment]
Hello everyone,

@saleel thanks for the fix, 
Updating to version 6.0.1 worked fine for me.

Command: **npm i react-native-super-grid@latest**
