### ISSUE TITLE
how to add press item handler

### ISSUE THREAD

**Issue by thelastsummer** [saleel/react-native-super-grid#22]
how can I add item click handler
I tried to this way, but not working

<GridView
	 itemDimension={150}
	 items={this.items}
	 style={styles.gridView}
	 renderItem={item => (
         <TouchableHighlight
                    style={styles.screen_button}
                    onPress={this._onPressItem(item.index)}>
                    <Text style={styles.screen_button_text}>{item.name}</Text> 
        </TouchableHighlight>
)}
/>

**Comment by saleel** [comment]
Click handler to what? Your code has no click handler anywhere.

The component render whatever you have in `renderItem`. If you want to have a button with click handler, you can do inside `renderItem`.

**Comment by dreindoRT** [comment]
I can't use onPress in gridview tag, how to implement?

**Comment by saleel** [comment]
GridView itself dont have onPress. You can have it for each or selected items in the GridView.

GridView only renders whatever you have in renderItem. You can have a button with click handler, you should do it inside renderItem.
