### ISSUE TITLE
Is SectionHeader supported?

### ISSUE THREAD

**Issue by Angelk90** [saleel/react-native-super-grid#28]
@saleel : 
Hi, is SectionHeader supported?
being that I have to do a page system.
Example:
Page 1: the first twenty results
Page 2: the second twenty results
...

**Comment by saleel** [comment]
Not our of the box as of now. I guess you can implement pagination in your component and  dynamically pass different items (items for selected page) to the GridView

**Comment by Angelk90** [comment]
@saleel : I did not understand.
I read this article: https://medium.com/@darylrowland/reactnative-listview-with-section-headers-99a6714282c3
I tried to change the module like this:

```
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { View, ListView, Dimensions, ViewPropTypes, Text } from 'react-native';
import { chunkArray } from './utils';

class SuperGrid extends Component {
  constructor(props) {
    super(props);
    this.renderRow = this.renderRow.bind(this);
    this.onLayout = this.onLayout.bind(this);
    this.getDimensions = this.getDimensions.bind(this);
    this.state = this.getDimensions();
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.itemDimension !== this.props.itemDimension) {
      this.setState({
        ...this.getDimensions(this.state.totalDimension, nextProps.itemDimension),
      });
    }
  }

  onLayout(e) {
    const { staticDimension, horizontal } = this.props;
    if (!staticDimension) {
      const { width, height } = e.nativeEvent.layout || {};

      this.setState({
        ...this.getDimensions(horizontal ? height : width),
      });
    }
  }

  getDimensions(lvDimension, itemDim) {
    const { itemWidth, spacing, fixed, staticDimension, horizontal } = this.props;
    let itemDimension = itemDim || this.props.itemDimension;
    if (itemWidth) {
      itemDimension = itemWidth;
      console.warn('React Native Super Grid - property "itemWidth" is depreciated. Use "itemDimension" instead.');
    }

    const dimension = horizontal ? 'height' : 'width';
    const totalDimension = lvDimension || staticDimension || Dimensions.get('window')[dimension];
    const itemTotalDimension = itemDimension + spacing;
    const availableDimension = totalDimension - spacing; // One spacing extra
    const itemsPerRow = Math.floor(availableDimension / itemTotalDimension);
    const containerDimension = availableDimension / itemsPerRow;


    return {
      totalDimension,
      itemDimension,
      spacing,
      itemsPerRow,
      containerDimension,
      fixed,
    };
  }

  renderVerticalRow(data, sectionId, rowId) {
    const { itemDimension, spacing, containerDimension, fixed } = this.state;
    const columnStyle = {
      flexDirection: 'column',
      paddingLeft: spacing,
    };
    const rowStyle = {
      height: containerDimension,
      paddingBottom: spacing,
    };
    let itemStyle = {};
    if (fixed) {
      itemStyle = {
        height: itemDimension,
        alignSelf: 'center',
        paddingBottom: spacing,
      };
    }

    return (
      <View style={columnStyle}>
        {(data || []).map((item, i) => (
          <View key={`${rowId}_${i}`} style={rowStyle}>
            <View style={itemStyle}>
              {this.props.renderItem(item, i)}
            </View>
          </View>
        ))}
      </View>
    );
  }

  renderHorizontalRow(data, sectionId, rowId) {
    const { itemDimension, containerDimension, spacing, fixed } = this.state;
    const rowStyle = {
      flexDirection: 'row',
      paddingLeft: spacing,
      paddingBottom: spacing,
    };
    const columnStyle = {
      flexDirection: 'column',
      justifyContent: 'center',
      width: containerDimension,
      paddingRight: spacing,
    };
    let itemStyle = {};
    if (fixed) {
      itemStyle = {
        width: itemDimension,
        alignSelf: 'center',
      };
    }

    return (
      <View style={rowStyle}>
        {(data || []).map((item, i) => (
          <View key={`${rowId}_${i}`} style={columnStyle}>
            <View style={itemStyle}>
              {this.props.renderItem(item, i)}
            </View>
          </View>
        ))}
      </View>
    );
  }

  renderRow(data, sectionId, rowId) {
    const { horizontal } = this.props;
    if (horizontal) {
      return this.renderVerticalRow(data, sectionId, rowId);
    }
    return this.renderHorizontalRow(data, sectionId, rowId);
  }

  convertArrayToMap(el) {
    var CategoryMap = {};
    el.forEach(Item => {
      if (!CategoryMap[Item.page]) CategoryMap[Item.page] = [];
      CategoryMap[Item.page].push(Item);
    });
    return CategoryMap;
  }

  renderSectionHeader(sectionData, page) {
    console.log(sectionData)
    return (<Text style={{fontWeight: "700"}}>{page}</Text>)
  }

  render() {
    const { items, style, renderItem, spacing, fixed,
      itemDimension, horizontal, ...props } = this.props;
    const { itemsPerRow } = this.state;

    const rows = chunkArray(items, itemsPerRow);
    const ds = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2, sectionHeaderHasChanged: (s1, s2) => s1 !== s2 });

    return (
      <ListView
        enableEmptySections
        style={[{ paddingTop: spacing }, style]}
        onLayout={this.onLayout}
        dataSource={ds.cloneWithRowsAndSections(this.convertArrayToMap(rows))}
        renderSectionHeader={this.renderSectionHeader}
        renderRow={this.renderRow}
        {...props}
        horizontal={horizontal}
      />
    );
  }
}

SuperGrid.propTypes = {
  renderItem: PropTypes.func.isRequired,
  items: PropTypes.arrayOf(PropTypes.any).isRequired,
  itemDimension: PropTypes.number,
  itemWidth: PropTypes.number, // for backward compatibility
  fixed: PropTypes.bool,
  spacing: PropTypes.number,
  style: ViewPropTypes.style,
  staticDimension: PropTypes.number,
  horizontal: PropTypes.bool,
};

SuperGrid.defaultProps = {
  fixed: false,
  itemDimension: 120,
  itemWidth: null,
  spacing: 10,
  style: {},
  staticDimension: undefined,
  horizontal: false,
};

export default SuperGrid;

```
Where am I doing wrong?
Can not SectionHeader be implemented in this case on react-native-super-grid?

**Comment by saleel** [comment]
Is it not working like this? I haven't tested the code, but looks like it should work.

Did the console.log in renderSectionHeader print anything?

**Comment by Angelk90** [comment]
@saleel :  If I print page, it returns undefined. If I print sectionData, it prints an array of element arrays.

**Comment by saleel** [comment]
I am not sure what data you are actually passing to the grid.

In `convertArrayToMap` can you put console.log for CategoryMap before the return statement and paste the output.

**Comment by saleel** [comment]
The problem is in covertArrayToMap, what you receive as Item is not a single item. Its an array of grouped items which would go as one row in super grid (because we group items based on screen size and treat them as one ListView item).

The below code would make it work, provided all items in group has same page. I am taking the page from first item of the array, but you can customize

`import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { View, ListView, Dimensions, ViewPropTypes, Text } from 'react-native';
import { chunkArray } from './utils';

class SuperGrid extends Component {
  constructor(props) {
    super(props);
    this.renderRow = this.renderRow.bind(this);
    this.onLayout = this.onLayout.bind(this);
    this.getDimensions = this.getDimensions.bind(this);
    this.state = this.getDimensions();
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.itemDimension !== this.props.itemDimension) {
      this.setState({
        ...this.getDimensions(
          this.state.totalDimension,
          nextProps.itemDimension
        ),
      });
    }
  }

  onLayout(e) {
    const { staticDimension, horizontal } = this.props;
    if (!staticDimension) {
      const { width, height } = e.nativeEvent.layout || {};

      this.setState({
        ...this.getDimensions(horizontal ? height : width),
      });
    }
  }

  getDimensions(lvDimension, itemDim) {
    const {
      itemWidth,
      spacing,
      fixed,
      staticDimension,
      horizontal,
    } = this.props;
    let itemDimension = itemDim || this.props.itemDimension;
    if (itemWidth) {
      itemDimension = itemWidth;
      console.warn(
        'React Native Super Grid - property "itemWidth" is depreciated. Use "itemDimension" instead.'
      );
    }

    const dimension = horizontal ? 'height' : 'width';
    const totalDimension =
      lvDimension || staticDimension || Dimensions.get('window')[dimension];
    const itemTotalDimension = itemDimension + spacing;
    const availableDimension = totalDimension - spacing; // One spacing extra
    const itemsPerRow = Math.floor(availableDimension / itemTotalDimension);
    const containerDimension = availableDimension / itemsPerRow;

    return {
      totalDimension,
      itemDimension,
      spacing,
      itemsPerRow,
      containerDimension,
      fixed,
    };
  }

  renderVerticalRow(data, sectionId, rowId) {
    const { itemDimension, spacing, containerDimension, fixed } = this.state;
    const columnStyle = {
      flexDirection: 'column',
      paddingLeft: spacing,
    };
    const rowStyle = {
      height: containerDimension,
      paddingBottom: spacing,
    };
    let itemStyle = {};
    if (fixed) {
      itemStyle = {
        height: itemDimension,
        alignSelf: 'center',
        paddingBottom: spacing,
      };
    }

    return (
      <View style={columnStyle}>
        {(data || []).map((item, i) => (
          <View key={`${rowId}_${i}`} style={rowStyle}>
            <View style={itemStyle}>
              {this.props.renderItem(item, i)}
            </View>
          </View>
        ))}
      </View>
    );
  }

  renderHorizontalRow(data, sectionId, rowId) {
    const { itemDimension, containerDimension, spacing, fixed } = this.state;
    const rowStyle = {
      flexDirection: 'row',
      paddingLeft: spacing,
      paddingBottom: spacing,
    };
    const columnStyle = {
      flexDirection: 'column',
      justifyContent: 'center',
      width: containerDimension,
      paddingRight: spacing,
    };
    let itemStyle = {};
    if (fixed) {
      itemStyle = {
        width: itemDimension,
        alignSelf: 'center',
      };
    }

    return (
      <View style={rowStyle}>
        {(data || []).map((item, i) => (
          <View key={`${rowId}_${i}`} style={columnStyle}>
            <View style={itemStyle}>
              {this.props.renderItem(item, i)}
            </View>
          </View>
        ))}
      </View>
    );
  }

  renderRow(data, sectionId, rowId) {
    const { horizontal } = this.props;
    if (horizontal) {
      return this.renderVerticalRow(data, sectionId, rowId);
    }
    return this.renderHorizontalRow(data, sectionId, rowId);
  }

  convertArrayToMap(el) {
    var CategoryMap = {};
    el.forEach(Item => {
      // console.log(Item)
      if (!CategoryMap[Item[0].page]) CategoryMap[Item[0].page] = [];
      CategoryMap[Item[0].page].push(Item);
    });
    // console.log(CategoryMap);
    return CategoryMap;
  }

  renderSectionHeader(sectionData, page) {
    console.log(page);
    return <Text style={{ fontWeight: '700' }}>{page}</Text>;
  }

  render() {
    const {
      items,
      style,
      renderItem,
      spacing,
      fixed,
      itemDimension,
      horizontal,
      ...props
    } = this.props;
    const { itemsPerRow } = this.state;

    const rows = chunkArray(items, itemsPerRow);
    const ds = new ListView.DataSource({
      rowHasChanged: (r1, r2) => r1 !== r2,
      sectionHeaderHasChanged: (s1, s2) => s1 !== s2,
    });

    return (
      <ListView
        enableEmptySections
        style={[{ paddingTop: spacing }, style]}
        onLayout={this.onLayout}
        dataSource={ds.cloneWithRowsAndSections(this.convertArrayToMap(rows))}
        renderSectionHeader={this.renderSectionHeader}
        renderRow={this.renderRow}
        {...props}
        horizontal={horizontal}
      />
    );
  }
}

SuperGrid.propTypes = {
  renderItem: PropTypes.func.isRequired,
  items: PropTypes.arrayOf(PropTypes.any).isRequired,
  itemDimension: PropTypes.number,
  itemWidth: PropTypes.number, // for backward compatibility
  fixed: PropTypes.bool,
  spacing: PropTypes.number,
  style: ViewPropTypes.style,
  staticDimension: PropTypes.number,
  horizontal: PropTypes.bool,
};

SuperGrid.defaultProps = {
  fixed: false,
  itemDimension: 120,
  itemWidth: null,
  spacing: 10,
  style: {},
  staticDimension: undefined,
  horizontal: false,
};

export default SuperGrid;
`


I know this is not the correct solution but might help you for now.

**Comment by Angelk90** [comment]
@saleel : Thx, I do not understand why it does not work that way.
I did this, I added the prop sectionHeader, tell me what you think.

```
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { View, ListView, Dimensions, ViewPropTypes, Text } from 'react-native';
import { chunkArray } from './utils';

class SuperGrid extends Component {
  constructor(props) {
    super(props);
    this.renderRow = this.renderRow.bind(this);
    this.onLayout = this.onLayout.bind(this);
    this.getDimensions = this.getDimensions.bind(this);
    this.state = this.getDimensions();
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.itemDimension !== this.props.itemDimension) {
      this.setState({
        ...this.getDimensions(
          this.state.totalDimension,
          nextProps.itemDimension
        ),
      });
    }
  }

  onLayout(e) {
    const { staticDimension, horizontal } = this.props;
    if (!staticDimension) {
      const { width, height } = e.nativeEvent.layout || {};

      this.setState({
        ...this.getDimensions(horizontal ? height : width),
      });
    }
  }

  getDimensions(lvDimension, itemDim) {
    const {
      itemWidth,
      spacing,
      fixed,
      staticDimension,
      horizontal,
    } = this.props;
    let itemDimension = itemDim || this.props.itemDimension;
    if (itemWidth) {
      itemDimension = itemWidth;
      console.warn(
        'React Native Super Grid - property "itemWidth" is depreciated. Use "itemDimension" instead.'
      );
    }

    const dimension = horizontal ? 'height' : 'width';
    const totalDimension =
      lvDimension || staticDimension || Dimensions.get('window')[dimension];
    const itemTotalDimension = itemDimension + spacing;
    const availableDimension = totalDimension - spacing; // One spacing extra
    const itemsPerRow = Math.floor(availableDimension / itemTotalDimension);
    const containerDimension = availableDimension / itemsPerRow;

    return {
      totalDimension,
      itemDimension,
      spacing,
      itemsPerRow,
      containerDimension,
      fixed,
    };
  }

  renderVerticalRow(data, sectionId, rowId) {
    const { itemDimension, spacing, containerDimension, fixed } = this.state;
    const columnStyle = {
      flexDirection: 'column',
      paddingLeft: spacing,
    };
    const rowStyle = {
      height: containerDimension,
      paddingBottom: spacing,
    };
    let itemStyle = {};
    if (fixed) {
      itemStyle = {
        height: itemDimension,
        alignSelf: 'center',
        paddingBottom: spacing,
      };
    }

    return (
      <View style={columnStyle}>
        {(data || []).map((item, i) => (
          <View key={`${rowId}_${i}`} style={rowStyle}>
            <View style={itemStyle}>
              {this.props.renderItem(item, i)}
            </View>
          </View>
        ))}
      </View>
    );
  }

  renderHorizontalRow(data, sectionId, rowId) {
    const { itemDimension, containerDimension, spacing, fixed } = this.state;
    const rowStyle = {
      flexDirection: 'row',
      paddingLeft: spacing,
      paddingBottom: spacing,
    };
    const columnStyle = {
      flexDirection: 'column',
      justifyContent: 'center',
      width: containerDimension,
      paddingRight: spacing,
    };
    let itemStyle = {};
    if (fixed) {
      itemStyle = {
        width: itemDimension,
        alignSelf: 'center',
      };
    }

    return (
      <View style={rowStyle}>
        {(data || []).map((item, i) => (
          <View key={`${rowId}_${i}`} style={columnStyle}>
            <View style={itemStyle}>
              {this.props.renderItem(item, i)}
            </View>
          </View>
        ))}
      </View>
    );
  }

  renderRow(data, sectionId, rowId) {
    const { horizontal } = this.props;
    if (horizontal) {
      return this.renderVerticalRow(data, sectionId, rowId);
    }
    return this.renderHorizontalRow(data, sectionId, rowId);
  }

  convertArrayToMap(el) {
    var CategoryMap = {};
    el.forEach(Item => {
      //console.log(Item)
      if (!CategoryMap[Item[0].page]) CategoryMap[Item[0].page] = [];
      CategoryMap[Item[0].page].push(Item);
    });
    // console.log(CategoryMap);
    return CategoryMap;
  }

  renderSectionHeader(sectionData, page) {
    if(page!=="undefined")
    return (
      <Text style={{
        paddingLeft: 15,
        paddingBottom: 15,
        color: '#fff',
        fontWeight: 'bold',
        textShadowColor: 'rgba(255,255,255,1)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 4,
      }}>
        Pagina: {page}
      </Text>
    );
    else return;
  }

  render() {
    const {
      items,
      style,
      renderItem,
      spacing,
      fixed,
      itemDimension,
      horizontal,
      sectionHeader,
      ...props
    } = this.props;
    const { itemsPerRow } = this.state;

    const rows = chunkArray(items, itemsPerRow);
    const ds = (sectionHeader) ? new ListView.DataSource({
      rowHasChanged: (r1, r2) => r1 !== r2,
      sectionHeaderHasChanged: (s1, s2) => s1 !== s2
    }) : new ListView.DataSource({
      rowHasChanged: (r1, r2) => r1 !== r2
    });

    const dataSource = (sectionHeader) ? ds.cloneWithRowsAndSections(this.convertArrayToMap(rows)) : ds.cloneWithRows(rows);
    const renderSectionHeader = (sectionHeader) ? this.renderSectionHeader : null;

    return (
      <ListView
        enableEmptySections
        style={[{ paddingTop: spacing }, style]}
        onLayout={this.onLayout}
        dataSource={dataSource}
        renderSectionHeader={renderSectionHeader}
        renderRow={this.renderRow}
        {...props}
        horizontal={horizontal}
      />
    );
  }
}

SuperGrid.propTypes = {
  renderItem: PropTypes.func.isRequired,
  items: PropTypes.arrayOf(PropTypes.any).isRequired,
  itemDimension: PropTypes.number,
  itemWidth: PropTypes.number, // for backward compatibility
  fixed: PropTypes.bool,
  spacing: PropTypes.number,
  style: ViewPropTypes.style,
  staticDimension: PropTypes.number,
  horizontal: PropTypes.bool,
  sectionHeader: PropTypes.bool
};

SuperGrid.defaultProps = {
  fixed: false,
  itemDimension: 120,
  itemWidth: null,
  spacing: 10,
  style: {},
  staticDimension: undefined,
  horizontal: false,
  sectionHeader: false
};

export default SuperGrid;

```

**Comment by saleel** [comment]
Is this not working?

Are you suggesting a general solution? If so `page` shouldn't be hardcoded. Instead of sectionHeader prop, we can have sectionHeaderKey which is the key (in item list) that has the value to be used for header.

**Comment by Angelk90** [comment]
@saleel : It works, at least it seems so. ;)
I thought if anyone could serve, I allowed myself to share it.

sectionHeader if it is false, it remains what it is, that is, what you have set up.
sectionHeader if it's true, then use it.

Yes, you could use sectionHeaderKey, which if set then uses it if not, no.
- I would also set a prop renderSectionHeader, which sets the text it should have.

**Comment by saleel** [comment]
Yes.

But before we add this is in the original code, we need to handle cases where all items in a row is not of a single header.

**Comment by Angelk90** [comment]
@saleel : 

I'm not sure I understood correctly?
I use this:
   ```
 const ds = (sectionHeader) ? new ListView.DataSource({
      rowHasChanged: (r1, r2) => r1 !== r2,
      sectionHeaderHasChanged: (s1, s2) => s1 !== s2
    }) : new ListView.DataSource({
      rowHasChanged: (r1, r2) => r1 !== r2
    });

    const dataSource = (sectionHeader) ? ds.cloneWithRowsAndSections(this.convertArrayToMap(rows)) : ds.cloneWithRows(rows);
    const renderSectionHeader = (sectionHeader) ? this.renderSectionHeader : null;
```

**Comment by saleel** [comment]
All this is correct.

But in convertArrayToMap we are taking the page from the first item in the row. This assumption is only true if all the items in one given row has same page.

We will have to modify the chunkArray function to handle cases like this.

**Comment by Angelk90** [comment]
@saleel : I understand what you mean, at least I think.
The question is not easy, in my opinion it depends a lot on how the user wants to use sectionHeader and the grid.
I used it in the simplest way, in the sense I make a call feth to some bees.
That for every call I always get the same number of results, for example 10.
The number of results at most can be different in the last call I make, since the system of the bees of the elements is divided into pages.
So in my case it does not change anything.

But the problem arises if it is used differently.
Consider that the user has a list of ingredients.
Each ingredient has an example property:
Fruits, vegetables, artificial, spices ...
In this case, the number of elements that possesses one of these specifications is different, if you want to use this as a key.
So I do not know what to say.

**Comment by saleel** [comment]
Yea, I will try to include a proper option to handle all cases in the next release.
