### ISSUE TITLE
Set custom height to the grid images

### ISSUE THREAD

**Issue by durgaganesh** [saleel/react-native-super-grid#35]
I need to show my grid images in 4:5 ratio (width:height). So, I need to set own height (width/4*5) value to the grid images at runtime. Is there s way to do this?

  ```
<GridView
          spacing={0}
          itemDimension={screenWidth/2}
          items = {this.renderItems()}
          style={styles.gridView}
          renderItem={this.renderGrid.bind(this)}
       />
```

**Comment by saleel** [comment]
I think you will have to take a fork and update the source code a bit.

In line 89 and 126, you can pass the itemDimensions variable to  `{this.props.renderItem(item, i)}`, and in your renderItem implementation you can use this width to set the height.
