### ISSUE TITLE
Arrange item per row

### ISSUE THREAD

**Issue by ommyan** [saleel/react-native-super-grid#42]
nice grid!, greate work.

I gave a question, how to manual set item per row, example render view like this
[1] [2]  [3] // 3 item per row fixed
[4] [5] [6]
[7] [8] [9]

thanks

**Comment by andersonaddo** [comment]
For that, you'd probably want to find the length of the device's screen and divide it by the number of elements you want per row.
Try looking at this page, maybe it can help
[Screen dimensions in React Native](https://facebook.github.io/react-native/docs/dimensions.html)

**Comment by saleel** [comment]
There would be other libraries to achieve this.
The purpose of this library is to render maximum possible items based on the fixed item width and available screen size.

What you want maybe achievable in this library (like @andersonaddo  said), but all those calculations it do would be unnecessary for this use case. So I would suggest a different library unless there is a real reason you want to stick with this one.

**Comment by ommyan** [comment]
ok thank Andesonaddo and saleel

**Comment by YousefAlsbaihi** [comment]
Maybe this is too late to answer but for future reference you can do the following: 

```
import { Dimensions } from "react-native";
...
const { width, height } = Dimensions.get("window");
...
const ws = width/4
...

<FlatGrid
     itemDimension={ws}
     items={items}
     ....

```
this way you have divided the screen width by 4 and it will have 3 items in one row.

**Comment by saleel** [comment]
Yes, that should work. Thanks
