### ISSUE TITLE
Getting the index of the renderItem

### ISSUE THREAD

**Issue by nHiRanZ** [saleel/react-native-super-grid#44]
Hi, this component is superb. Is there a way to get the item index of `renderItem`?

Something like in `FlatList`?

Ex:
```
<FlatList
    scrollEnabled={this.state.itemList.length > 3}
    data={this.state.itemList}
    keyExtractor={item => item.id}
    renderItem={({item, index}) => this.renderItem(item, index)} //Like This?
/>
```

**Comment by saleel** [comment]
Yes, in the current renderItem the second parameter is the index of the item.
`renderItem={(item, index) => {}}`

In the next major version this signature will be changed to match with the FlatList signature (only one  parameter which is an object that has item, index...etc)

**Comment by nHiRanZ** [comment]
Hi Saleel, thank you. But the current implementation seems to give the `index` according to the rows.

I have 7 items in my `GridView` and they are arranged as 3 items per row. This gives the index always as follows.

> 2018-06-06 10:03:01.003 [info][tid:com.facebook.react.JavaScript] 0
> 2018-06-06 10:03:01.004 [info][tid:com.facebook.react.JavaScript] 1
> 2018-06-06 10:03:01.004 [info][tid:com.facebook.react.JavaScript] 2
> 2018-06-06 10:03:01.009 [info][tid:com.facebook.react.JavaScript] 0
> 2018-06-06 10:03:01.010 [info][tid:com.facebook.react.JavaScript] 1
> 2018-06-06 10:03:01.010 [info][tid:com.facebook.react.JavaScript] 2
> 2018-06-06 10:03:01.016 [info][tid:com.facebook.react.JavaScript] 0

**Comment by saleel** [comment]
Yea, you are right. That was meant for styling each rows from what I remember. Sorry

For now, you will have to create a fork and add this functionality yourself.

On this line https://github.com/saleel/react-native-super-grid/blob/master/index.js#L135, renderRow can also receive and `index` parameter. 
Pass this to both renderVerticalRow and renderHorizontalRow (as rowIndex).
Inside the implementation of renderHorizontalRow (https://github.com/saleel/react-native-super-grid/blob/master/index.js#L127) you can edit it to something like `{this.props.renderItem(item, rowIndex * this.state.itemsPerRow + i)}`

**Comment by andersonaddo** [comment]
Was thinking of fixing this myself. @nHiRanZ if you intend to, so ahead. Otherwise, give me the go ahead and I'll quickly make a PQ to fix this.

**Comment by nHiRanZ** [comment]
@andersonaddo Hi mate, you can go ahead. I'm using a global variable instead of the index. Works for my setup.

**Comment by saleel** [comment]
PR merged.
Install version 2.4 and you will get proper index as the second parameter.
