### ISSUE TITLE
Fixed sectionList that changes text

### ISSUE THREAD

**Issue by Angelk90** [saleel/react-native-super-grid#46]
@saleel : Using this module it would be possible to do something like this:
https://drive.google.com/file/d/1sbTDz7v2MDiFbCZTOmLAw-fSG6dKAdUT/view

Sample code: https://snack.expo.io/S1yAIQilQ

**Comment by andersonaddo** [comment]
The nature of your layout defeats the purpose of using the `SuperSectionGridLayout`. This module is meant for creating lists formatted as **grids**, but yours is completely linear. In this case, you should just use the native `SectionList` (which is meant for linear layouts and faster) instead.
