### ISSUE TITLE
Header sections 

### ISSUE THREAD

**Issue by AlmogRnD** [saleel/react-native-super-grid#5]
Is it possible to add or create header sections? I would like to load photos but in a date section

**Comment by saleel** [comment]
You mean you want to a header section to the grid? Right now, No.

You can still do it by creating a new component and placing your header and this Grid as children.

**Comment by AlmogRnD** [comment]
Thanks not sure that well work, the scroll behavior would be wired wanted something like this 
<img width="860" alt="screen shot 2017-07-13 at 6 56 12 am" src="https://user-images.githubusercontent.com/169507/28169842-650990b8-6798-11e7-815a-48de1a6ebf89.png">

**Comment by saleel** [comment]
Yes, you are right.

I will try to do this in the next version. I am bit busy with other projects at the moment so it will take few weeks. If you are doing it yourself, send a pull request and I will approve.

**Comment by AlmogRnD** [comment]
I don't I will have the chance to do a PR, have a tight deadline

**Comment by saleel** [comment]
No problem. I will have a look at it.
Closing the issue for now.
