### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'array.reduce')

### ISSUE THREAD

**Issue by tehjnito** [saleel/react-native-super-grid#50]
this error gets thrown using my own code and even with the example provided.
I'm assuming it has something to do with that method in the utils files, but I'm uncertain.

![screenshot_1529700914](https://user-images.githubusercontent.com/27317894/41798988-5579085c-7635-11e8-9282-adcbedcd1802.png)

**Comment by saleel** [comment]
Demo code is working fine for me. Just tested.

This error would happen if you are not passing a valid array as the items prop. Please check again.

**Comment by anztrax** [comment]
i can repro the issue : 
in my case this caused by you install this super grid module, but you forgot to re run ```react-native run-android``` , so the react native didn't know the module yet..., solve by re run ```react-native run-android``` , done 🎉
