### ISSUE TITLE
How i can set the position of the arrow buttons?

### ISSUE THREAD

**Issue by GuillermoGuevara** [saleel/react-native-super-grid#52]

**Comment by saleel** [comment]
Please provide some description. What arrow buttons?

**Comment by GuillermoGuevara** [comment]
Sorry, the arrows buttons to change betweens views, not de navigation dots

**Comment by saleel** [comment]
I don't think you question is related to this library. There are no arrow buttons here.
For general questions, please ask at StackOverflow.
