### ISSUE TITLE
Spacing prop only affect horizontal spacing

### ISSUE THREAD

**Issue by himmetpp** [saleel/react-native-super-grid#53]
When i changed spacing to 3, horizontal space becomes 3 but vertical space stays 10. There is a marginBottom: 10 styling on one of the views which is not affected from spacing prop.

**Comment by saleel** [comment]
Working fine for me with the example we have in Readme.
Below is the screenshot with spacing 3.

Please check again. If you still think there is some issue, please post your code here.


![simulator screen shot - iphone 6 - 2018-07-13 at 00 00 11](https://user-images.githubusercontent.com/13466197/42656250-bcaca2b8-862f-11e8-9f67-8c3b52a9e91e.png)

**Comment by himmetpp** [comment]
Upps, I found out that it occurs because of another code. There wasn't any problem with react-native-super-grid. Thank you for reply, sorry for taking time :)

**Comment by elmcapp** [comment]
I am having the same issue. When I change the spacing it only change horizontal. That when I use Fixed prop. I use the Fixed prop so that I can keep everything as a square

**Comment by saleel** [comment]
@elmcapp Spacing should work for both horizontal and landscape. `Fixed` is to use the exact `itemDimension` you pass and not to adjust based to available width.
