### ISSUE TITLE
Use a different method for deep cloning

### ISSUE THREAD

**Issue by visualfanatic** [saleel/react-native-super-grid#56]
Current method uses `JSON.parse` & `JSON.stringify` to deep clone the `sections` data:
https://github.com/saleel/react-native-super-grid/blob/48df8eab9a874c90c8c482c7dd4402f82b9d92e7/SuperGridSectionList.js#L112-L113

The problem is that it will not clone keys with assigned functions as their values. After I moved from the `SectionList` to the `SuperGridSectionList` I got a lot `undefined` properties in the `renderItem` and `renderSectionHeader` methods.

@saleel would you consider using something like [`lodash.clonedeep`](https://www.npmjs.com/package/lodash.clonedeep) instead of the method I described above to solve this issue?

**Comment by andersonaddo** [comment]
No problem, I can quickly fix that for ya.

**Comment by andersonaddo** [comment]
#57 Submitted

**Comment by saleel** [comment]
#57 Merged to master.
Version 2.4.3 released to npm

**Comment by visualfanatic** [comment]
Thank you for such a quick change and release!
