### ISSUE TITLE
Is it possible to make an infinite list with this component?

### ISSUE THREAD

**Issue by jacm80** [saleel/react-native-super-grid#58]
I try use this component I am trying to use this component with an infinite list as it is handled with the FlatList but the onEndReachedThreshold works only once.

`import React, { Component } from 'react';
import { View, Text, Image, ActivityIndicator } from 'react-native';
import GridView from 'react-native-super-grid';
import PropTypes from 'prop-types';

class CardMarkResume extends Component {

   constructor(props) {
      super(props);
      // this._infinityList = React.createRef();
      this.viewabilityConfig = {
         waitForInteraction: true,
         viewAreaCoveragePercentThreshold: 0.1
      };
   }

_renderFooter = () => {
   const { loading } = this.props;
   if (!loading) return null;
   return (
      <View style={{ paddingVertical: 20, borderTopWidth: 1, borderColor: '#CED0CE' }} >
         <ActivityIndicator animating size="large" />
      </View>
   );
}

// uri:'https://unsplash.it/400/400/?random'

render() {

   const { data, refreshing, loading, handleLoadMore } = this.props;

   return (
      <GridView
         viewabilityConfig={this.viewabilityConfig}
         itemDimension={130}
         items={data}
         style={styles.gridView}
         onEndReachedThreshold={0.1} // compatible con android no tocar
         onEndReached={handleLoadMore}
         refreshing={refreshing}
         loading={loading}
         ListFooterComponent={this._renderFooter}
         renderItem={item => (
            <View style={styles.itemContainer}>
               <Image style={{ position: 'absolute', height: 200, width: 200, resizeMode: 'cover' }} source={item.imagen} />
               <View style={{ backgroundColor: 'rgba(51, 51, 51, 0.8)', padding: 6, flex: 1, maxHeight: 40, alignSelf: 'stretch' }}>
                  <Text numberOfLines={1} style={styles.itemName}>{item.Title}</Text>
                  <Text style={styles.itemCode}>$ {item.Precio}</Text>
               </View>
            </View>
         )}
      />
   );
}

}

const styles = {
   gridView: {
      paddingTop: 25,
      flex: 1,
   },
   itemContainer: {
      justifyContent: 'flex-end',
      padding: 10,
      height: 150,
      position: 'relative',
      overflow: 'hidden'
   },
   itemName: {
      fontSize: 16,
      color: '#fff',
      fontFamily: 'DINCond'
   },
   itemCode: {
      fontFamily: 'DINMedium',
      fontSize: 12,
      color: '#fff',
   },
};

CardMarkResume.propTypes = {
   data: PropTypes.array.isRequired,
   refreshing: PropTypes.bool,
   loading: PropTypes.bool,
   handleLoadMore: PropTypes.func
};

export { CardMarkResume };`

**Comment by saleel** [comment]
This is working fine for me. I tested with your example (slightly modified to make it work)

```
import PropTypes from 'prop-types';

class CardMarkResume extends Component {

    constructor(props) {
        super(props);
        // this._infinityList = React.createRef();

        this.state = {
            data: [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2]
        }
        this.viewabilityConfig = {
            waitForInteraction: true,
            viewAreaCoveragePercentThreshold: 0.1
        };

        this.handleLoadMore = this.handleLoadMore.bind(this);
    }

    _renderFooter = () => {
        const {
            loading
        } = this.props;
        if (!loading) return null;
        return ( <
            View style = {
                {
                    paddingVertical: 20,
                    borderTopWidth: 1,
                    borderColor: '#CED0CE'
                }
            }
            />


        );
    }

    handleLoadMore() {
        console.log('handleLoadMore')
        this.setState({
            data: this.state.data.concat(this.state.data)
        })
    }


    // uri:'https://unsplash.it/400/400/?random'

    render() {

        const {
            refreshing,
            loading
        } = this.props;


        return ( <
            GridView viewabilityConfig = {
                this.viewabilityConfig
            }
            itemDimension = {
                130
            }
            items = {
                this.state.data
            }
            style = {
                styles.gridView
            }
            onEndReachedThreshold = {
                0.1
            } // compatible con android no tocar
            onEndReached = {
                this.handleLoadMore
            }
            refreshing = {
                refreshing
            }
            loading = {
                loading
            }
            ListFooterComponent = {
                this._renderFooter
            }
            renderItem = {
                item => ( <
                    View style = {
                        {
                            height: 200,
                            width: 200,
                        }
                    } >
                    <
                    Image style = {
                        {
                            position: 'absolute',
                            height: 200,
                            width: 200,
                            resizeMode: 'cover'
                        }
                    }
                    source = {
                        item.imagen
                    }
                    /> <
                    View style = {
                        {
                            backgroundColor: 'rgba(51, 51, 51, 0.8)',
                            padding: 6,
                            flex: 1,
                            maxHeight: 40,
                            alignSelf: 'stretch'
                        }
                    } > {
                        item.Title
                    } {
                        item.Precio
                    } <
                    /View> <
                    /View>

                )
            }
            />
        );
    }

}

const styles = {
    gridView: {
        paddingTop: 25,
        flex: 1,
    },
    itemContainer: {
        justifyContent: 'flex-end',
        padding: 10,
        height: 150,
        position: 'relative',
        overflow: 'hidden'
    },
    itemName: {
        fontSize: 16,
        color: '#fff',
        fontFamily: 'DINCond'
    },
    itemCode: {
        fontFamily: 'DINMedium',
        fontSize: 12,
        color: '#fff',
    },
};

CardMarkResume.propTypes = {
    data: PropTypes.array.isRequired,
    refreshing: PropTypes.bool,
    loading: PropTypes.bool,
    handleLoadMore: PropTypes.func
};

export default CardMarkResume;
```

**Comment by jacm80** [comment]
thanks my friend, I have not had a chance to try because I'm full and pending other parts of the application, I resolved using a flatlist, but I want to use your component because it adapts very well to the design.

**Comment by jacm80** [comment]
tested and working, your component look **very good**!

<img width="319" alt="captura de pantalla 2018-08-06 a la s 12 23 01" src="https://user-images.githubusercontent.com/2110146/43728725-f9f33c52-9973-11e8-92cb-8ea6fc90e0a8.png">

**Comment by andersonaddo** [comment]
Looking good indeed! 👌🏾
