### ISSUE TITLE
Clear grid view

### ISSUE THREAD

**Issue by AlmogRnD** [saleel/react-native-super-grid#6]
Is there a method to clear or remove items from the gridview, for example I have an api call that updates with new photos when that method is called I would like to delete the current contents of the gird view

**Comment by saleel** [comment]
You can keep the results of your API call in a state variable of the parent component and set this state variable as the data source for the Grid.
So every time the method is called and state is updated, the Grid will re-render.

Did you already try this? If this is not working please post a sample code and I will have a look.

**Comment by AlmogRnD** [comment]
Yes, I'm doing something similar however there is a delay until the new images loads which looks like a bug. It would be better to have some kind of clear method which I can call on unmount. 

Here is a gif with the issue 
![gridview-issue](https://user-images.githubusercontent.com/169507/28951485-23a0dac0-7880-11e7-8ff9-df793d23db6e.gif)
  
As you can see there is a delay until the new images are loaded

**Comment by saleel** [comment]
Yes, this look like a bug. I will have a look today.

**Comment by AlmogRnD** [comment]
You can close this I went ahead and moved to a different package

**Comment by saleel** [comment]
I did have a look at this anyway. I think this is the issue of the native Image component and not this library. I guess the result would be same even if you used the native ListView (which is what this component uses internally)

I believe using an image loader like [this](https://github.com/oblador/react-native-image-progress) should solve the problem.
