### ISSUE TITLE
Section header is overlap with item on iOS

### ISSUE THREAD

**Issue by Desz01ate** [saleel/react-native-super-grid#60]
I'm try to render the grid by this snippet

    const gridSectionRenderer = ({ section }) => {
      return (
        <Text style={[styles.CommonHeaderText, { fontSize: 25 }]}>
          {section.SectionName}
        </Text>
      );
    };

        <SuperGridSectionList
              itemDimension={130}
              sections={this.state.data}
              style={styles.gridView}
              renderItem={gridViewRenderer}
              renderSectionHeader={gridSectionRenderer}
            />

and it's work just fine on Android
![screenshot_1535511220](https://user-images.githubusercontent.com/9304487/44762596-cb951780-ab71-11e8-8227-cb66d791543a.png)

 still, the problem only occur on iOS just like the picture below
![prob](https://user-images.githubusercontent.com/9304487/44762644-f3847b00-ab71-11e8-8a77-ac0d7a1629d4.png)

any idea what happening or causing this? any help would be appreciated.

**Comment by andersonaddo** [comment]
We’re gonna have to see `gridViewRenderer` to be of any real help.

**Comment by Desz01ate** [comment]
here's a `gridViewRenderer`


const gridViewRenderer = ({ item, index }) => {
      return (
        <TouchableHighlight 
          style={styles.itemContainer}>
          <View>
            <Image
              style={{ width: 130, height: 130 }}
              source={{
                uri: "data:image/png;base64," + item.Product_Image
              }}
            />
            <Text style={styles.itemName}>{item.Product_Name}</Text>
          </View>
        </TouchableHighlight>
      );
    };

**Comment by Desz01ate** [comment]
the problem seem to occur with the example too 
fyi, the testing device is iPhone 5S

![image](https://user-images.githubusercontent.com/9304487/44770403-263e6b80-ab92-11e8-8677-44c04aac645a.png)

**Comment by saleel** [comment]
This is the default behaviour of SectionList (which is internally used) in iOS ([reference](https://facebook.github.io/react-native/docs/sectionlist#rendersectionheader)).

You can disable this by passing `stickySectionHeadersEnabled={false}` to SuperGridSectionList

Also, the default behavior will look good if you put a background color to section header, and remove margins/padding on top

**Comment by Desz01ate** [comment]
I'll try this, thank you!
