### ISSUE TITLE
FlatList props are type error

### ISSUE THREAD

**Issue by keenjoe007** [saleel/react-native-super-grid#65]
When used in typescript, props that can be used with FlatList become type error (eg `onEndReached`, `onEndReachedThreshold` etc....).
Is this supposed to be? Is it supposed to be used in type script?
I am avoiding it using `@ts-ignore` now.
please tell me if there is a way to extend it well.

**Comment by saleel** [comment]
I guess you have to add type definitions here - https://github.com/saleel/react-native-super-grid/blob/master/index.d.ts

I don't use typescript, so can't do it myself for now.
You can raise a pull if you are fixing this.

**Comment by keenjoe007** [comment]
OK! Thanks!
