### ISSUE TITLE
itemContainerStyle does not work with SuperGridSectionList

### ISSUE THREAD

**Issue by adrianm86** [saleel/react-native-super-grid#69]
I want to use jusifyContent: 'flex-start' inside itemContainerStyle in SuperGridSectionList, but no change occurs, continue using justifyContent: 'center'.

**Comment by ataillefer** [comment]
Can you please provide your code?

**Comment by saleel** [comment]
Are you trying to align the itemContainer to flex-start while using in fixed width mode? This is not supported for now.

I am closing this anyway because of inactivity. If you are still facing issue, please add comment with more details, sample code, screenshots..etc
