### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by AlmogRnD** [saleel/react-native-super-grid#7]
First I wanted to say it's a great component, second is there a method that can be used to load more items I would like to setup an infinite scroll where I load more photos from an API call. 

Either a method when the end is reached or something like onLoadMoreAsync which is called at the end.

**Comment by saleel** [comment]
Right now there is no such method. But this is a great feature and I will consider adding it.

**Comment by AlmogRnD** [comment]
No worries I'm I have moved to using - https://github.com/danke77/react-native-easy-listview-gridview 

It has what I need

**Comment by ahmedabadie** [comment]
The component uses `ListView` and passes all props to it. So using `ListView`'s `onEndReached` should work out-of-the-box.

**Comment by saleel** [comment]
It should. I haven't tested it though.
And an easier implementation might be possible by wrapping `onEndReached`.

I am planning to switch to FlatList and will try to do this after.

**Comment by hiteshagja** [comment]
As you are switched to FlatList ... Can you please add onEndReached?
