### ISSUE TITLE
refresh?

### ISSUE THREAD

**Issue by karanpratapsingh** [saleel/react-native-super-grid#71]
can we call a refresh function like in standard scrollview in react native?

**Comment by saleel** [comment]
This component is build on top of ListView.

All additional props are passed down to the internal ListView component. You should be able to use [RefreshControl](https://facebook.github.io/react-native/docs/refreshcontrol) for this purpose.

**Comment by sm1th** [comment]
@saleel @karanpratapsingh This component is based off of FlatList/SectionList, which has the onRefresh prop. Use it like this:
```
    private renderUnitList = () => {
        return (
            <GridView
                itemDimension={150}
                style={styles.container}
                items={this.state.units.units}
                renderItem={this._renderItem}
                onRefresh={this.getUnitsFromAPI} // function that updates the list
                refreshing={this.state.refreshing} // set this to true if still updating list, false otherwise
            />
        );
    }
```
