### ISSUE TITLE
Fit to content ability for GridView container 

### ISSUE THREAD

**Issue by unip** [saleel/react-native-super-grid#72]
There is currently a `staticDimension` prop to set the `GridView` container to specific value of its height or width. But how if the case is to set the height or width of the container to fit the content? Is there any workaround?

Thanks.

**Comment by saleel** [comment]
You mean all items have different dimensions? Maybe you can put your contents inside a `View` and style the `View` accordingly. If you have some sample code and expected screenshots/mockup, I can help.

**Comment by unip** [comment]
![mockup](https://user-images.githubusercontent.com/6513444/49708184-22c28200-fc61-11e8-8c02-d47c15ec5dbb.png)
Here is my expected mockup. Items have same dimensions. I want the main/ outer container of `GridView` can fit its height dynamically to the items. So when the `GridView` has more items, the height will adjust itself.

**Comment by saleel** [comment]
Sorry for the delay. Was very busy.

I think
 you achieve this with simple style fix.

Try something like this

 ```
<View style={{ flex: 1 }}>
      <GridView
        itemDimension={130}
        items={items}
        style={{ flex: 1 }}
        renderItem={item => (
          <View style={[styles.itemContainer, { backgroundColor: item.code }]}>
            <Text style={styles.itemName}>{item.name}</Text>
            <Text style={styles.itemCode}>{item.code}</Text>
          </View>
        )}
      />

          <Text style={{ flex: 1 }}>test</Text>
      </View>
    );
```



![simulator screen shot - iphone 6 - 2018-12-14 at 20 30 44](https://user-images.githubusercontent.com/13466197/50015092-26e2fc80-ffdf-11e8-8e76-dcad5ebc3f78.png)
