### ISSUE TITLE
undefined is not an object  (evaluating 'item.code'

### ISSUE THREAD

**Issue by kukode** [saleel/react-native-super-grid#74]
i have issue 

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, {Component} from 'react';
import {StyleSheet, Text, View,TouchableOpacity} from 'react-native';
import {Container,Header, Title, Body} from 'native-base'
import GridView from 'react-native-super-grid';

export default class App extends Component {
  items = [
    { id: 1, name: 'TURQUOISE', code: '#1abc9c' }
  ];

  xyz = ({item}) => {
    

      return(
        <TouchableOpacity>
        <View style={[styles.itemContainer, { backgroundColor: item.code }]}>
          <Text style={styles.itemName}>{item.name}</Text>
          <Text style={styles.itemCode}>{item.code}</Text>
        </View>
        </TouchableOpacity>
      )
      
    
  }
  
  render() {
    
    return (
      <Container>
        <Header>
          <Body>
            <Title>
              Menu
            </Title>
          </Body>
        </Header>
        <GridView
        itemDimension={130}
        items={this.items}
        style={styles.gridView}
        renderItem={this.xyz}
      />
       
      </Container>
    );
  }
}

const styles = StyleSheet.create({
  gridView: {
    paddingTop: 25,
    flex: 1,
  },
  itemContainer: {
    justifyContent: 'flex-end',
    borderRadius: 5,
    padding: 10,
    height: 150,
  },
  itemName: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '600',
  },
  itemCode: {
    fontWeight: '600',
    fontSize: 12,
    color: '#fff',
  },
});
``

**Comment by saleel** [comment]
`xyz = ({item}) => {` should be `xyz = (item) => {`

Presently GridView is based on ListView. This will be changed in next major release to match with FlatList API

**Comment by gds3k3** [comment]
Thank you for this Grid, used it before without problems. 

Now I'm having the same issue:

    "react-native-super-grid": "^3.0.4",
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",

Relevant code:
`
import { FlatGrid } from 'react-native-super-grid'; 
var items_wi = [	
				{  
					name: 'Estado',					
					img: imgEstado,
					code: '#008833',
				},	{
					name: 'Activar',
					img: imgActivar,
					code: '#33aa33',
				},	{
					name: 'Desactivar',
					img: imgDesactivar,
					code: '#aa3333',
}]

				<FlatGrid key={ky}
					itemDimension={130}
					items={items_wi}
					style={{flex: 1, paddingTop: 25}}
					renderItem={({btn, index}) => (
						<TouchableOpacity 
							onPress={() => this._btnClick(item)} 
							underlayColor="blue">
							<View style={{ justifyContent: 'center', alignItems: 'center',	borderRadius: 5, padding: 10, height: 150, backgroundColor: 'red' }} >
								{console.log('btn: ' + btn.name + ' items_wi.length:' + items_wi.length)}
								<Image
									style={{ width: 80,	height: 80 }}
									source={ btn.img }
								/>						
								<Text style={{fontSize: 16, color: '#fff', fontWeight: '600'}}>{btn.name}</Text>
							</View>
						</TouchableOpacity>			 	
					)}
				/>
`
Console out using signature: renderItem={( btn, index ) => ( 

[13:19:07] btn: undefined items_wi.length:3
[13:19:07] btn: undefined items_wi.length:3
[13:19:07] btn: undefined items_wi.length:3

Console out using signature: renderItem={({btn, index}) => ( 

[13:35:23] TypeError: TypeError: undefined is not an object (evaluating 'btn.name')

**Comment by saleel** [comment]
You are destructuring `{btn, index}` on first param of renderItem function. That param object definitely don't have a property called btn. It will have item, index...etc as per the signature

Change it to `({ item: btn, index }) =>` and it should work. Also, please create a new issue instead of reopening old ones.
