### ISSUE TITLE
can i change the item height

### ISSUE THREAD

**Issue by geminiyellow** [saleel/react-native-super-grid#75]
i notice that , in line 99 , there is a `itemStyle` warp the `renderItem` , so when i cannot use style like `height: '100%'`, @saleel why don't you let it use as `style=[itemContainerStyle, (fixed && itemStyle)]`
 
https://github.com/saleel/react-native-super-grid/blob/fd1a807e44179cee962e9d9f64f7bcfe7cd02b6a/SuperGridSectionList.js#L99-L103

**Comment by saleel** [comment]
I will have a look. I am in the process of making next major version, and will consider this.

Closing the issue for now

**Comment by geminiyellow** [comment]
@saleel ok thank you
