### ISSUE TITLE
can't display grid view element on ios

### ISSUE THREAD

**Issue by waterflower124** [saleel/react-native-super-grid#76]
This react-native-super-grid component works well on android.
But in my case, grid items doesn't display on ios.
I'm using following code:

constructor(props) {
    this.state = {
        items: [],
    }
};

componentWillMount() {
    self = this;
    fetch("https://... ... ... ", {
        .then(response => response.json())
        .then(data => {
            self.setState({items: data});
        }
    })
}
render() {
... ... ... ...
    <GridView
      itemDimension={130}
      items={items}
      renderItem={item => (<Text>{item}</Text>)}
    />
... ... ... ...
}

In this case, anything doesn't show. But if I set items statically then it works, that is, 

constructor(props) {
    this.state = {
        items: [
          { name: 'TURQUOISE', code: '#1abc9c' }, { name: 'EMERALD', code: '#2ecc71' },
          { name: 'TURQUOISE1', code: '#1abc9c' }, { name: 'EMERALD', code: '#2ecc71' }
        ];,
    }
};

then can see gird view with two elements.

How can I show although items has a value? Anyone who know this issue, pls help me.

Thanks.

**Comment by saleel** [comment]
I am not sure what you are trying to achieve by this `renderItem={item => ({item})}`. The example code works fine both on android and ios, even when populated with network call. Issue could be with your renderItem, or the state was not set properly as you expected. This don't look like an issue with the component.
