### ISSUE TITLE
Is it possible to disable floating section header?

### ISSUE THREAD

**Issue by feizalbadri** [saleel/react-native-super-grid#80]
Hi @saleel, this library is so great! I would like to use it for my new project. However I haven't see any clue to disable the floating section header? Do you plan to add the functionality in the future? 

Looking forward to hearing from you.

Thanks!

**Comment by saleel** [comment]
I assume you want a non-sticky header in SectionGrid. You can use `stickySectionHeadersEnabled={false}` for that.

All additional props you pass are passed on to the underlying SectionList. [stickySectionHeadersEnabled](https://facebook.github.io/react-native/docs/sectionlist#stickysectionheadersenabled) is actually a SectionList prop.
