### ISSUE TITLE
add migration guide from 2.X to 3.X

### ISSUE THREAD

**Issue by otusweb** [saleel/react-native-super-grid#83]
I have the 2.X version and wondering how to upgrade to 3.X.

It would be great to have a migration guide in the documentation

Thanks for putting this control together

**Comment by saleel** [comment]
Added here - https://github.com/saleel/react-native-super-grid#v2-to-v3-migration

Let me know once you do the migration. Just to make sure I have not missed any point there.

**Comment by otusweb** [comment]
@saleel thanks for the quick update.
