### ISSUE TITLE
Does it support extradata too ?

### ISSUE THREAD

**Issue by amitbravo** [saleel/react-native-super-grid#84]
just wondering if this supports extradata property as flatlist ?

**Comment by saleel** [comment]
It should work as all additional props are passed down to FlatList, though I have not tested it myself. Let me know if you try it and don't work.

**Comment by stepupithubapp** [comment]
heyyyyy @saleel 
it's not working in section grid

**Comment by saleel** [comment]
@stepupithubapp It should work SectionGrid as well since the extra data is passed to SectionList inside. Are you able to produce the desired effect by passing extraData when using the SectionList (instead of SectionGrid)? If it works for SectionList it should work for SectionGrid as well.
