### ISSUE TITLE
Support for React Native Web

### ISSUE THREAD

**Issue by Shriram-Balaji** [saleel/react-native-super-grid#85]
Hey, thanks for this super useful library. Since the docs do not explicitly specify any support regarding react-native-web, I'd like to know if its compatible with it or not.

**Comment by deefourple** [comment]
Depending on how you handle your primitive types, you should be able to get it working fairly painlessly for web. I'm currently using it for web, without any issues or additional configuration.

**Comment by ningacoding** [comment]
I have an issue for web, when using web on mobile FlatGrid stops the scroll when user starts scrolling inside FlatList elements.

**Comment by ningacoding** [comment]
> I have an issue for web, when using web on mobile FlatGrid stops the scroll when user starts scrolling inside FlatList elements.
> 
> i tried to remove scroll for FlatGrid to release touch event
> 
> ```
>         nestedScrollEnabled={false}
>         scrollEnabled={false}
>         canCancelContentTouches={false}
> ```
> 
> But not working.
> 
> when i disable this CSS property
> 
> ![image](https://private-user-images.githubusercontent.com/17342546/363442870-6d7ab61c-bcdb-4816-b3c5-b3a83a2e740a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNDI0MjksIm5iZiI6MTcyNTE0MjEyOSwicGF0aCI6Ii8xNzM0MjU0Ni8zNjM0NDI4NzAtNmQ3YWI2MWMtYmNkYi00ODE2LWIzYzUtYjNhODNhMmU3NDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDIyMDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYWIxNWZiMjQxMTEwM2NhOGY4MTFmNmJkOWYzZWNlMmFkNjI1NGJmNGQxM2E4MjY2MjYxOWQ2ZjYzZTg1YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CXYFtRCuuDn0xjMWtshrIkYrUthzhH7fonTEVcqNcHE)
> 
> the component enable scrolling from FLatGrid.
> 
> Any idea which component adds that CSS prop?

i was able to make it work with

```
        nestedScrollEnabled={false}
        scrollEnabled
```
