### ISSUE TITLE
Trying to use ImageBackground instead of BackgroundColor

### ISSUE THREAD

**Issue by GodwinEbikwo** [saleel/react-native-super-grid#86]
Trying to use ImageBackground instead of BackgroundColor and want to pass each image to a new screen using props, not working. PLease any help will be usefull

**Comment by saleel** [comment]
I did not understand what you are asking. The content of each grid view item is completely in your hands and you can render any RN component. Please provide sample code and expected results if you think the issue is within this library.

**Comment by mohmdalfaha** [comment]
I am kinda getting the same issue where rendering a custom component that requires props to be passed into it. 

@GodwinEbikwo  Have you solved your issue or have any updates on this ??

**Comment by saleel** [comment]
@mohmdalfaha Please create a new issue if you notice any problems. Commenting on old/closed issues might go unnoticed.

Also include some sample code (and screenshots if applicable) when you submit an issue.
