### ISSUE TITLE
Gap issue when adding more content to Grid

### ISSUE THREAD

**Issue by Rob2k9** [saleel/react-native-super-grid#92]
I am using onEndReached to load more content into an array and this has the correct effect and new items are added to the list but it comes with a problem when the items are added to the list there is a gap between the old items and the new items because of the buffer added to the end of the list

is there a way to remove this from the list ?

**Comment by saleel** [comment]
Can you provide a screenshot and sample code?

I think it has to be fixed inside the Component. I will look in to this.

**Comment by saleel** [comment]
I have tested this and didn't find any additional gap when new items are added. There is only the normal spacing which is present between all the items/rows.

Sample here - [https://snack.expo.io/r1N3G29yH](https://snack.expo.io/r1N3G29yH)
