### ISSUE TITLE
How to load the list of image while scrolling with count 20

### ISSUE THREAD

**Issue by nihp** [saleel/react-native-super-grid#94]
I need to show the list of images in Flatgrid. In my implementation, at a time all the images get loaded. It takes more time. 

So kindly give any reference or solution to show the list of image loaded upto 20 and then 20 and so on.

**Comment by saleel** [comment]
You can use [onEndReached](https://facebook.github.io/react-native/docs/flatlist#onendreached) prop for this.
In the parent component keep your data in the state (20 item array initially) and pass this state variable as `data` prop to FlatGrid. Whenever `onEndReached` is triggered you can update data state by adding 20 more items, which will in turn update the FlatGrid.
You can find examples for this in FlatList. The syntax and implementation will be similar.
