### ISSUE TITLE
[TS] Missing  some props described on readme

### ISSUE THREAD

**Issue by Grohden** [saleel/react-native-super-grid#95]
As stated on the readme:
> All additional props you pass will be passed on to the internal FlatList/SectionList. This means you can make use of various props and methods like ListHeaderComponent, onEndReached, onRefresh...etc. While these are not tested for compatibility, most of them should work as expected.

But the declaration file actually doesn't merge the `FlatList ` or the `SectionListProps` on the declarations, this could be solved by this:

```typescript
import {
  ...others,
  FlatListProps, 
  SectionListProps
} from 'react-native'

// Older ts versions don't have this type
type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;

type FlatListAllowedProps<ItemType = any> = Omit<FlatListProps<ItemType>,
  | 'data'
  | 'someOtherPropNotAllowed'
>

/**
 * React Native Super Grid Properties
 */
export interface FlatGridProps<ItemType = any> extends FlatListAllowedProps<ItemType> {
...rest

// Same for section
```

I'm not openning a PR cuz this may be wrong, I'm not sure if the props should be exactly the same, it's likely that the grid/section overide some props, but i don't know exacly which ones

**Comment by saleel** [comment]
All other props are not tested explicitly, so they are not "officially" supported. They will be passed down to FlatList and SectionList, but if any if these props depends on item index (for example), then the result might not be as expected. So, adding to type definitions might not be a good idea.

I don't use TS myself. Is it not possible to pass props that are not defined in d.ts file?

**Comment by Grohden** [comment]
@saleel we can pass props that are not defined in the `d.ts`, but the typecheck will fail, and typecheck is mostly why everyone is using TS

I understand that they're not officially supported, but they can be used in js... so what is the diff from the normal js 'support' for these props?

Of course that wrong types would be worse, but since we could be using a union from the original types and excluding some 'bad'/required props from the original definition (the `data` prop) I think that is fine to let ts devs use them as js devs already do

**Comment by saleel** [comment]
@Grohden That sounds fine. It would be great if you can raise a PR for this. I personally don't use typescript is not very good in making type definitions.
