### ISSUE TITLE
Does not return the section index when an item is clicked.

### ISSUE THREAD

**Issue by reyanshmishra** [saleel/react-native-super-grid#96]
I have data in a array something like this
`let images = [
  {
    "data": [
      {
        "id": 332,
        "isSelected": false
      },
      {
        "id": 366,
        "isSelected": false
      }
    ],
    "date": "2019-06-21"
  },
  {
    "data": [
      {
        "id": 365,
        "isSelected": false
      },
      {
        "id": 367,
        "isSelected": false
      },
      {
        "id": 368,
        "isSelected": false
      },
      {
        "id": 369,
        "isSelected": false
      },
      {
        "id": 370,
        "isSelected": false
      },
      {
        "id": 371,
        "isSelected": false
      },
      {
        "id": 375,
        "isSelected": false
      }
    ],
    "date": "2019-06-21"
  }
]`

now whenever I click on an item I want to toggle `the isSelected` property of that item but I am unable to do so as in the `renderItem({item,index,rowIndex,section})` method I am only getting the `index` which is the index of the item in section and `rowIndex` which is the index of the row after being rendered on the device but there is no property which is called `sectionIndex` so that I can manipulate the exact item like below.

`images[sectionIndex].data[itemIndex]`

is there any other way to achieve what I want?

**Comment by saleel** [comment]
You are getting the entire `section` object in the callback. You can put some id for each section, if you want to identify then in the callback. 
In your example  if the `date` is a unique key, you can do something like
```
({ section, itemIndex }) => images.find(i => i.date === section.date).data[itemIndex]
```

Having `sectionIndex` could make it easier, but it also not present in the [renderItem](https://facebook.github.io/react-native/docs/sectionlist#renderitem) method of `SectionList`. The function signature is kept very similar to corresponding official components.

**Comment by reyanshmishra** [comment]
I had to modify the library to get it working with section index.
Thanks
