### ISSUE TITLE
Prop onEndReach not working?

### ISSUE THREAD

**Issue by nachocifu** [saleel/react-native-super-grid#99]
Hi! First of all great module!

I believe found a bug on the props not being passed correctly to the child list element when using FlatGrid.

On my code:
`<Fragment>  
                <FlatGrid  
                    itemDimension={this.state.itemSize}  
                    fixed={true}  
                    items={this.state.items}  
                    renderItem={this.renderItem}
                    onEndReach={Reactotron.warn('List end Reached')}
                    // onEndReachedThreshold={0.5}
                />
                <Button onPress={this.fetchCameraRoll} title="FETCH"/>
                <Button buttonStyle={{backgroundColor: '#f15f67'}}
                        onPress={() => this.props.navigation.navigate('ImageEdition')} title="CONTINUAR"/>
</Fragment>`

The onEndReach is only triggered when loading more images to this.state.items when using the Button on the bottom. The idea is to load more items automatically.

Note: Using commit 2fdeb0142d24f0f4f79eae95b1e61ba8c7e4fa6d

**Comment by saleel** [comment]
I don't think this is related to FlatGrid. It will pass all extra props directly to FlatList.

See if setting [onEndReachedThreshold](https://facebook.github.io/react-native/docs/flatlist#onendreachedthreshold) can help
